package net.nishat.model.AM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 25 11:33:42 PKT 2015
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void refreshEmpFormData();

    void refreshSubordFormData();

    void refreshPeerFormData();
}
