package net.nishat.model.Search;

import javax.faces.context.FacesContext;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 17 09:55:12 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TotalSubsImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TotalSubsImpl() {
    }

    /**
     * Returns the bind variable value for emp_id.
     * @return bind variable value for emp_id
     */
    public String getemp_id() {
        FacesContext fctx = FacesContext.getCurrentInstance();
        HttpServletRequest req =
            (HttpServletRequest)fctx.getExternalContext().getRequest();
        HttpSession session = req.getSession();
        return (String)session.getAttribute("user_id");
    }

    /**
     * Sets <code>value</code> for bind variable emp_id.
     * @param value value to bind as emp_id
     */
    public void setemp_id(String value) {
        setNamedWhereClauseParam("emp_id", value);
    }
}
