package net.nishat.model.Search;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 25 09:26:00 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_SearchEmployeeUnderLineManagerRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        EmployeeId,
        FullNameChild,
        Department,
        Designation,
        DateOfJoining,
        EmployeeNumber,
        SupervisorId;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int FULLNAMECHILD = AttributesEnum.FullNameChild.index();
    public static final int DEPARTMENT = AttributesEnum.Department.index();
    public static final int DESIGNATION = AttributesEnum.Designation.index();
    public static final int DATEOFJOINING = AttributesEnum.DateOfJoining.index();
    public static final int EMPLOYEENUMBER = AttributesEnum.EmployeeNumber.index();
    public static final int SUPERVISORID = AttributesEnum.SupervisorId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VO_SearchEmployeeUnderLineManagerRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute EmployeeId.
     * @return the EmployeeId
     */
    public Number getEmployeeId() {
        return (Number) getAttributeInternal(EMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EmployeeId.
     * @param value value to set the  EmployeeId
     */
    public void setEmployeeId(Number value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FullNameChild.
     * @return the FullNameChild
     */
    public String getFullNameChild() {
        return (String) getAttributeInternal(FULLNAMECHILD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FullNameChild.
     * @param value value to set the  FullNameChild
     */
    public void setFullNameChild(String value) {
        setAttributeInternal(FULLNAMECHILD, value);
    }


    /**
     * Gets the attribute value for the calculated attribute Department.
     * @return the Department
     */
    public String getDepartment() {
        return (String) getAttributeInternal(DEPARTMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Department.
     * @param value value to set the  Department
     */
    public void setDepartment(String value) {
        setAttributeInternal(DEPARTMENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Designation.
     * @return the Designation
     */
    public String getDesignation() {
        return (String) getAttributeInternal(DESIGNATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Designation.
     * @param value value to set the  Designation
     */
    public void setDesignation(String value) {
        setAttributeInternal(DESIGNATION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DateOfJoining.
     * @return the DateOfJoining
     */
    public String getDateOfJoining() {
        return (String) getAttributeInternal(DATEOFJOINING);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DateOfJoining.
     * @param value value to set the  DateOfJoining
     */
    public void setDateOfJoining(String value) {
        setAttributeInternal(DATEOFJOINING, value);
    }


    /**
     * Gets the attribute value for the calculated attribute EmployeeNumber.
     * @return the EmployeeNumber
     */
    public String getEmployeeNumber() {
        return (String) getAttributeInternal(EMPLOYEENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EmployeeNumber.
     * @param value value to set the  EmployeeNumber
     */
    public void setEmployeeNumber(String value) {
        setAttributeInternal(EMPLOYEENUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SupervisorId.
     * @return the SupervisorId
     */
    public Number getSupervisorId() {
        return (Number) getAttributeInternal(SUPERVISORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SupervisorId.
     * @param value value to set the  SupervisorId
     */
    public void setSupervisorId(Number value) {
        setAttributeInternal(SUPERVISORID, value);
    }
}
