package net.nishat.model.EO;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 15 14:04:48 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EO_XxLmApFormImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    @Override
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        this.setLmApFormId(new SequenceImpl("xx_lm_ap_form_seq",
                                                   getDBTransaction()).getSequenceNumber());
        
        
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        EmpId {
            public Object get(EO_XxLmApFormImpl obj) {
                return obj.getEmpId();
            }

            public void put(EO_XxLmApFormImpl obj, Object value) {
                obj.setEmpId((String)value);
            }
        }
        ,
        Lmid {
            public Object get(EO_XxLmApFormImpl obj) {
                return obj.getLmid();
            }

            public void put(EO_XxLmApFormImpl obj, Object value) {
                obj.setLmid((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(EO_XxLmApFormImpl obj) {
                return obj.getAttribute1();
            }

            public void put(EO_XxLmApFormImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(EO_XxLmApFormImpl obj) {
                return obj.getAttribute2();
            }

            public void put(EO_XxLmApFormImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(EO_XxLmApFormImpl obj) {
                return obj.getAttribute3();
            }

            public void put(EO_XxLmApFormImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(EO_XxLmApFormImpl obj) {
                return obj.getAttribute4();
            }

            public void put(EO_XxLmApFormImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(EO_XxLmApFormImpl obj) {
                return obj.getAttribute5();
            }

            public void put(EO_XxLmApFormImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(EO_XxLmApFormImpl obj) {
                return obj.getAttribute6();
            }

            public void put(EO_XxLmApFormImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(EO_XxLmApFormImpl obj) {
                return obj.getAttribute7();
            }

            public void put(EO_XxLmApFormImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        LmApFormId {
            public Object get(EO_XxLmApFormImpl obj) {
                return obj.getLmApFormId();
            }

            public void put(EO_XxLmApFormImpl obj, Object value) {
                obj.setLmApFormId((Number)value);
            }
        }
        ,
        Posted {
            public Object get(EO_XxLmApFormImpl obj) {
                return obj.getPosted();
            }

            public void put(EO_XxLmApFormImpl obj, Object value) {
                obj.setPosted((String)value);
            }
        }
        ,
        Comments {
            public Object get(EO_XxLmApFormImpl obj) {
                return obj.getComments();
            }

            public void put(EO_XxLmApFormImpl obj, Object value) {
                obj.setComments((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(EO_XxLmApFormImpl object);

        public abstract void put(EO_XxLmApFormImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EMPID = AttributesEnum.EmpId.index();
    public static final int LMID = AttributesEnum.Lmid.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int LMAPFORMID = AttributesEnum.LmApFormId.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EO_XxLmApFormImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("net.nishat.model.EO.EO_XxLmApForm");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for EmpId, using the alias name EmpId.
     * @return the EmpId
     */
    public String getEmpId() {
        return (String)getAttributeInternal(EMPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmpId.
     * @param value value to set the EmpId
     */
    public void setEmpId(String value) {
        setAttributeInternal(EMPID, value);
    }

    /**
     * Gets the attribute value for Lmid, using the alias name Lmid.
     * @return the Lmid
     */
    public String getLmid() {
        return (String)getAttributeInternal(LMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Lmid.
     * @param value value to set the Lmid
     */
    public void setLmid(String value) {
        setAttributeInternal(LMID, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for LmApFormId, using the alias name LmApFormId.
     * @return the LmApFormId
     */
    public Number getLmApFormId() {
        return (Number)getAttributeInternal(LMAPFORMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LmApFormId.
     * @param value value to set the LmApFormId
     */
    public void setLmApFormId(Number value) {
        setAttributeInternal(LMAPFORMID, value);
    }

    /**
     * Gets the attribute value for Posted, using the alias name Posted.
     * @return the Posted
     */
    public String getPosted() {
        return (String)getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Posted.
     * @param value value to set the Posted
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for Comments, using the alias name Comments.
     * @return the Comments
     */
    public String getComments() {
        return (String)getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Comments.
     * @param value value to set the Comments
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param lmApFormId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number lmApFormId) {
        return new Key(new Object[]{lmApFormId});
    }


}
