package net.nishat.model.EO;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 25 15:47:36 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EO_XxPeerApFormImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    @Override
    protected void create(AttributeList attributeList) {
        this.setPeerFormId(new SequenceImpl("xx_emp_ap_form_seq",
                                                   getDBTransaction()).getSequenceNumber());
        super.create(attributeList);
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PeerFormId {
            public Object get(EO_XxPeerApFormImpl obj) {
                return obj.getPeerFormId();
            }

            public void put(EO_XxPeerApFormImpl obj, Object value) {
                obj.setPeerFormId((Number)value);
            }
        }
        ,
        PId {
            public Object get(EO_XxPeerApFormImpl obj) {
                return obj.getPId();
            }

            public void put(EO_XxPeerApFormImpl obj, Object value) {
                obj.setPId((String)value);
            }
        }
        ,
        PName {
            public Object get(EO_XxPeerApFormImpl obj) {
                return obj.getPName();
            }

            public void put(EO_XxPeerApFormImpl obj, Object value) {
                obj.setPName((String)value);
            }
        }
        ,
        PEmployeeNo {
            public Object get(EO_XxPeerApFormImpl obj) {
                return obj.getPEmployeeNo();
            }

            public void put(EO_XxPeerApFormImpl obj, Object value) {
                obj.setPEmployeeNo((String)value);
            }
        }
        ,
        PDpt {
            public Object get(EO_XxPeerApFormImpl obj) {
                return obj.getPDpt();
            }

            public void put(EO_XxPeerApFormImpl obj, Object value) {
                obj.setPDpt((String)value);
            }
        }
        ,
        EvaluatedBy {
            public Object get(EO_XxPeerApFormImpl obj) {
                return obj.getEvaluatedBy();
            }

            public void put(EO_XxPeerApFormImpl obj, Object value) {
                obj.setEvaluatedBy((String)value);
            }
        }
        ,
        EvaluatorDpt {
            public Object get(EO_XxPeerApFormImpl obj) {
                return obj.getEvaluatorDpt();
            }

            public void put(EO_XxPeerApFormImpl obj, Object value) {
                obj.setEvaluatorDpt((String)value);
            }
        }
        ,
        EvaluatorEmployeeNo {
            public Object get(EO_XxPeerApFormImpl obj) {
                return obj.getEvaluatorEmployeeNo();
            }

            public void put(EO_XxPeerApFormImpl obj, Object value) {
                obj.setEvaluatorEmployeeNo((String)value);
            }
        }
        ,
        PRepectfulPoliteInConvo {
            public Object get(EO_XxPeerApFormImpl obj) {
                return obj.getPRepectfulPoliteInConvo();
            }

            public void put(EO_XxPeerApFormImpl obj, Object value) {
                obj.setPRepectfulPoliteInConvo((String)value);
            }
        }
        ,
        PEasyToWork {
            public Object get(EO_XxPeerApFormImpl obj) {
                return obj.getPEasyToWork();
            }

            public void put(EO_XxPeerApFormImpl obj, Object value) {
                obj.setPEasyToWork((String)value);
            }
        }
        ,
        PResponsible {
            public Object get(EO_XxPeerApFormImpl obj) {
                return obj.getPResponsible();
            }

            public void put(EO_XxPeerApFormImpl obj, Object value) {
                obj.setPResponsible((String)value);
            }
        }
        ,
        PCooperates {
            public Object get(EO_XxPeerApFormImpl obj) {
                return obj.getPCooperates();
            }

            public void put(EO_XxPeerApFormImpl obj, Object value) {
                obj.setPCooperates((String)value);
            }
        }
        ,
        PSharesInfo {
            public Object get(EO_XxPeerApFormImpl obj) {
                return obj.getPSharesInfo();
            }

            public void put(EO_XxPeerApFormImpl obj, Object value) {
                obj.setPSharesInfo((String)value);
            }
        }
        ,
        PeerComments {
            public Object get(EO_XxPeerApFormImpl obj) {
                return obj.getPeerComments();
            }

            public void put(EO_XxPeerApFormImpl obj, Object value) {
                obj.setPeerComments((String)value);
            }
        }
        ,
        Posted {
            public Object get(EO_XxPeerApFormImpl obj) {
                return obj.getPosted();
            }

            public void put(EO_XxPeerApFormImpl obj, Object value) {
                obj.setPosted((String)value);
            }
        }
        ,
        SubmitionDate {
            public Object get(EO_XxPeerApFormImpl obj) {
                return obj.getSubmitionDate();
            }

            public void put(EO_XxPeerApFormImpl obj, Object value) {
                obj.setSubmitionDate((Date)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(EO_XxPeerApFormImpl object);

        public abstract void put(EO_XxPeerApFormImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PEERFORMID = AttributesEnum.PeerFormId.index();
    public static final int PID = AttributesEnum.PId.index();
    public static final int PNAME = AttributesEnum.PName.index();
    public static final int PEMPLOYEENO = AttributesEnum.PEmployeeNo.index();
    public static final int PDPT = AttributesEnum.PDpt.index();
    public static final int EVALUATEDBY = AttributesEnum.EvaluatedBy.index();
    public static final int EVALUATORDPT = AttributesEnum.EvaluatorDpt.index();
    public static final int EVALUATOREMPLOYEENO = AttributesEnum.EvaluatorEmployeeNo.index();
    public static final int PREPECTFULPOLITEINCONVO = AttributesEnum.PRepectfulPoliteInConvo.index();
    public static final int PEASYTOWORK = AttributesEnum.PEasyToWork.index();
    public static final int PRESPONSIBLE = AttributesEnum.PResponsible.index();
    public static final int PCOOPERATES = AttributesEnum.PCooperates.index();
    public static final int PSHARESINFO = AttributesEnum.PSharesInfo.index();
    public static final int PEERCOMMENTS = AttributesEnum.PeerComments.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int SUBMITIONDATE = AttributesEnum.SubmitionDate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EO_XxPeerApFormImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("net.nishat.model.EO.EO_XxPeerApForm");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for PeerFormId, using the alias name PeerFormId.
     * @return the PeerFormId
     */
    public Number getPeerFormId() {
        return (Number)getAttributeInternal(PEERFORMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PeerFormId.
     * @param value value to set the PeerFormId
     */
    public void setPeerFormId(Number value) {
        setAttributeInternal(PEERFORMID, value);
    }

    /**
     * Gets the attribute value for PId, using the alias name PId.
     * @return the PId
     */
    public String getPId() {
        return (String)getAttributeInternal(PID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PId.
     * @param value value to set the PId
     */
    public void setPId(String value) {
        setAttributeInternal(PID, value);
    }

    /**
     * Gets the attribute value for PName, using the alias name PName.
     * @return the PName
     */
    public String getPName() {
        return (String)getAttributeInternal(PNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for PName.
     * @param value value to set the PName
     */
    public void setPName(String value) {
        setAttributeInternal(PNAME, value);
    }

    /**
     * Gets the attribute value for PEmployeeNo, using the alias name PEmployeeNo.
     * @return the PEmployeeNo
     */
    public String getPEmployeeNo() {
        return (String)getAttributeInternal(PEMPLOYEENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PEmployeeNo.
     * @param value value to set the PEmployeeNo
     */
    public void setPEmployeeNo(String value) {
        setAttributeInternal(PEMPLOYEENO, value);
    }

    /**
     * Gets the attribute value for PDpt, using the alias name PDpt.
     * @return the PDpt
     */
    public String getPDpt() {
        return (String)getAttributeInternal(PDPT);
    }

    /**
     * Sets <code>value</code> as the attribute value for PDpt.
     * @param value value to set the PDpt
     */
    public void setPDpt(String value) {
        setAttributeInternal(PDPT, value);
    }

    /**
     * Gets the attribute value for EvaluatedBy, using the alias name EvaluatedBy.
     * @return the EvaluatedBy
     */
    public String getEvaluatedBy() {
        return (String)getAttributeInternal(EVALUATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for EvaluatedBy.
     * @param value value to set the EvaluatedBy
     */
    public void setEvaluatedBy(String value) {
        setAttributeInternal(EVALUATEDBY, value);
    }

    /**
     * Gets the attribute value for EvaluatorDpt, using the alias name EvaluatorDpt.
     * @return the EvaluatorDpt
     */
    public String getEvaluatorDpt() {
        return (String)getAttributeInternal(EVALUATORDPT);
    }

    /**
     * Sets <code>value</code> as the attribute value for EvaluatorDpt.
     * @param value value to set the EvaluatorDpt
     */
    public void setEvaluatorDpt(String value) {
        setAttributeInternal(EVALUATORDPT, value);
    }

    /**
     * Gets the attribute value for EvaluatorEmployeeNo, using the alias name EvaluatorEmployeeNo.
     * @return the EvaluatorEmployeeNo
     */
    public String getEvaluatorEmployeeNo() {
        return (String)getAttributeInternal(EVALUATOREMPLOYEENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for EvaluatorEmployeeNo.
     * @param value value to set the EvaluatorEmployeeNo
     */
    public void setEvaluatorEmployeeNo(String value) {
        setAttributeInternal(EVALUATOREMPLOYEENO, value);
    }

    /**
     * Gets the attribute value for PRepectfulPoliteInConvo, using the alias name PRepectfulPoliteInConvo.
     * @return the PRepectfulPoliteInConvo
     */
    public String getPRepectfulPoliteInConvo() {
        return (String)getAttributeInternal(PREPECTFULPOLITEINCONVO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PRepectfulPoliteInConvo.
     * @param value value to set the PRepectfulPoliteInConvo
     */
    public void setPRepectfulPoliteInConvo(String value) {
        setAttributeInternal(PREPECTFULPOLITEINCONVO, value);
    }

    /**
     * Gets the attribute value for PEasyToWork, using the alias name PEasyToWork.
     * @return the PEasyToWork
     */
    public String getPEasyToWork() {
        return (String)getAttributeInternal(PEASYTOWORK);
    }

    /**
     * Sets <code>value</code> as the attribute value for PEasyToWork.
     * @param value value to set the PEasyToWork
     */
    public void setPEasyToWork(String value) {
        setAttributeInternal(PEASYTOWORK, value);
    }

    /**
     * Gets the attribute value for PResponsible, using the alias name PResponsible.
     * @return the PResponsible
     */
    public String getPResponsible() {
        return (String)getAttributeInternal(PRESPONSIBLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PResponsible.
     * @param value value to set the PResponsible
     */
    public void setPResponsible(String value) {
        setAttributeInternal(PRESPONSIBLE, value);
    }

    /**
     * Gets the attribute value for PCooperates, using the alias name PCooperates.
     * @return the PCooperates
     */
    public String getPCooperates() {
        return (String)getAttributeInternal(PCOOPERATES);
    }

    /**
     * Sets <code>value</code> as the attribute value for PCooperates.
     * @param value value to set the PCooperates
     */
    public void setPCooperates(String value) {
        setAttributeInternal(PCOOPERATES, value);
    }

    /**
     * Gets the attribute value for PSharesInfo, using the alias name PSharesInfo.
     * @return the PSharesInfo
     */
    public String getPSharesInfo() {
        return (String)getAttributeInternal(PSHARESINFO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PSharesInfo.
     * @param value value to set the PSharesInfo
     */
    public void setPSharesInfo(String value) {
        setAttributeInternal(PSHARESINFO, value);
    }

    /**
     * Gets the attribute value for PeerComments, using the alias name PeerComments.
     * @return the PeerComments
     */
    public String getPeerComments() {
        return (String)getAttributeInternal(PEERCOMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for PeerComments.
     * @param value value to set the PeerComments
     */
    public void setPeerComments(String value) {
        setAttributeInternal(PEERCOMMENTS, value);
    }

    /**
     * Gets the attribute value for Posted, using the alias name Posted.
     * @return the Posted
     */
    public String getPosted() {
        return (String)getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Posted.
     * @param value value to set the Posted
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for SubmitionDate, using the alias name SubmitionDate.
     * @return the SubmitionDate
     */
    public Date getSubmitionDate() {
        return (Date)getAttributeInternal(SUBMITIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubmitionDate.
     * @param value value to set the SubmitionDate
     */
    public void setSubmitionDate(Date value) {
        setAttributeInternal(SUBMITIONDATE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param peerFormId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number peerFormId) {
        return new Key(new Object[]{peerFormId});
    }


}
