package net.nishat.model.EO;

import javax.faces.context.FacesContext;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 16 09:31:53 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EO_XxEmpApFormImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    @Override
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        this.setEmpApFormId(new SequenceImpl("xx_emp_ap_form_seq",
                                                   getDBTransaction()).getSequenceNumber());
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        EmpApFormId {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getEmpApFormId();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setEmpApFormId((Number)value);
            }
        }
        ,
        DeptName {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getDeptName();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setDeptName((String)value);
            }
        }
        ,
        EmpNo {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getEmpNo();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setEmpNo((String)value);
            }
        }
        ,
        Qualification {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getQualification();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setQualification((String)value);
            }
        }
        ,
        Designation {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getDesignation();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setDesignation((String)value);
            }
        }
        ,
        Doj {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getDoj();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setDoj((Date)value);
            }
        }
        ,
        LastPromotionOn {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getLastPromotionOn();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setLastPromotionOn((Date)value);
            }
        }
        ,
        CommercialJudgment {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getCommercialJudgment();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setCommercialJudgment((String)value);
            }
        }
        ,
        ProductTechnicalKnowledge {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getProductTechnicalKnowledge();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setProductTechnicalKnowledge((String)value);
            }
        }
        ,
        TimeManagement {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getTimeManagement();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setTimeManagement((String)value);
            }
        }
        ,
        CommunicationSkills {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getCommunicationSkills();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setCommunicationSkills((String)value);
            }
        }
        ,
        DelegationSkills {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getDelegationSkills();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setDelegationSkills((String)value);
            }
        }
        ,
        MeetingDeadlines {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getMeetingDeadlines();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setMeetingDeadlines((String)value);
            }
        }
        ,
        CommitmentToWork {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getCommitmentToWork();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setCommitmentToWork((String)value);
            }
        }
        ,
        Creativity {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getCreativity();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setCreativity((String)value);
            }
        }
        ,
        ProblemSolving {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getProblemSolving();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setProblemSolving((String)value);
            }
        }
        ,
        TakingInitiative {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getTakingInitiative();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setTakingInitiative((String)value);
            }
        }
        ,
        DecisionMaking {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getDecisionMaking();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setDecisionMaking((String)value);
            }
        }
        ,
        TeamWork {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getTeamWork();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setTeamWork((String)value);
            }
        }
        ,
        DevelopingOthers {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getDevelopingOthers();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setDevelopingOthers((String)value);
            }
        }
        ,
        Leadership {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getLeadership();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setLeadership((String)value);
            }
        }
        ,
        Integrity {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getIntegrity();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setIntegrity((String)value);
            }
        }
        ,
        StabilityUnderPressure {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getStabilityUnderPressure();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setStabilityUnderPressure((String)value);
            }
        }
        ,
        AttitudeTowardsAuthority {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttitudeTowardsAuthority();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttitudeTowardsAuthority((String)value);
            }
        }
        ,
        Loyalty {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getLoyalty();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setLoyalty((String)value);
            }
        }
        ,
        AbilityToLearn {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAbilityToLearn();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAbilityToLearn((String)value);
            }
        }
        ,
        AcceptingChange {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAcceptingChange();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAcceptingChange((String)value);
            }
        }
        ,
        FilledById {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getFilledById();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setFilledById((String)value);
            }
        }
        ,
        FilledByEmail {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getFilledByEmail();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setFilledByEmail((String)value);
            }
        }
        ,
        Posted {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getPosted();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setPosted((String)value);
            }
        }
        ,
        EmpName {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getEmpName();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setEmpName((String)value);
            }
        }
        ,
        Remarks {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getRemarks();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        CoachesStuff {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getCoachesStuff();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setCoachesStuff((String)value);
            }
        }
        ,
        CommStyleOhr {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getCommStyleOhr();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setCommStyleOhr((String)value);
            }
        }
        ,
        Cooperates {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getCooperates();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setCooperates((String)value);
            }
        }
        ,
        DelegatesEffectivaly {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getDelegatesEffectivaly();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setDelegatesEffectivaly((String)value);
            }
        }
        ,
        EasyToWork {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getEasyToWork();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setEasyToWork((String)value);
            }
        }
        ,
        MotivatesForms {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getMotivatesForms();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setMotivatesForms((String)value);
            }
        }
        ,
        RemainPositive {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getRemainPositive();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setRemainPositive((String)value);
            }
        }
        ,
        RepectfulPoliteInConvo {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getRepectfulPoliteInConvo();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setRepectfulPoliteInConvo((String)value);
            }
        }
        ,
        Responsible {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getResponsible();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setResponsible((String)value);
            }
        }
        ,
        SharesInfo {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getSharesInfo();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setSharesInfo((String)value);
            }
        }
        ,
        TakeThingPersonally {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getTakeThingPersonally();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setTakeThingPersonally((String)value);
            }
        }
        ,
        GeneralComments {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getGeneralComments();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setGeneralComments((String)value);
            }
        }
        ,
        WorkAccuracy {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getWorkAccuracy();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setWorkAccuracy((String)value);
            }
        }
        ,
        SubmitionDate {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getSubmitionDate();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setSubmitionDate((Date)value);
            }
        }
        ,
        IsSecure {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getIsSecure();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setIsSecure((Number)value);
            }
        }
        ,
        LineManagerName {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getLineManagerName();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setLineManagerName((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute1();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute10();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute11();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute12();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute13();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute14();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute15();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute16 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute16();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute16((String)value);
            }
        }
        ,
        Attribute17 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute17();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute17((String)value);
            }
        }
        ,
        Attribute18 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute18();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute18((String)value);
            }
        }
        ,
        Attribute19 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute19();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute19((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute2();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute20 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute20();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute20((String)value);
            }
        }
        ,
        Attribute21 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute21();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute21((String)value);
            }
        }
        ,
        Attribute22 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute22();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute22((String)value);
            }
        }
        ,
        Attribute23 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute23();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute23((String)value);
            }
        }
        ,
        Attribute24 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute24();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute24((String)value);
            }
        }
        ,
        Attribute25 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute25();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute25((String)value);
            }
        }
        ,
        Attribute26 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute26();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute26((String)value);
            }
        }
        ,
        Attribute28 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute28();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute28((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute3();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute4();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute5();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute6();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute7();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute8();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(EO_XxEmpApFormImpl obj) {
                return obj.getAttribute9();
            }

            public void put(EO_XxEmpApFormImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(EO_XxEmpApFormImpl object);

        public abstract void put(EO_XxEmpApFormImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EMPAPFORMID = AttributesEnum.EmpApFormId.index();
    public static final int DEPTNAME = AttributesEnum.DeptName.index();
    public static final int EMPNO = AttributesEnum.EmpNo.index();
    public static final int QUALIFICATION = AttributesEnum.Qualification.index();
    public static final int DESIGNATION = AttributesEnum.Designation.index();
    public static final int DOJ = AttributesEnum.Doj.index();
    public static final int LASTPROMOTIONON = AttributesEnum.LastPromotionOn.index();
    public static final int COMMERCIALJUDGMENT = AttributesEnum.CommercialJudgment.index();
    public static final int PRODUCTTECHNICALKNOWLEDGE = AttributesEnum.ProductTechnicalKnowledge.index();
    public static final int TIMEMANAGEMENT = AttributesEnum.TimeManagement.index();
    public static final int COMMUNICATIONSKILLS = AttributesEnum.CommunicationSkills.index();
    public static final int DELEGATIONSKILLS = AttributesEnum.DelegationSkills.index();
    public static final int MEETINGDEADLINES = AttributesEnum.MeetingDeadlines.index();
    public static final int COMMITMENTTOWORK = AttributesEnum.CommitmentToWork.index();
    public static final int CREATIVITY = AttributesEnum.Creativity.index();
    public static final int PROBLEMSOLVING = AttributesEnum.ProblemSolving.index();
    public static final int TAKINGINITIATIVE = AttributesEnum.TakingInitiative.index();
    public static final int DECISIONMAKING = AttributesEnum.DecisionMaking.index();
    public static final int TEAMWORK = AttributesEnum.TeamWork.index();
    public static final int DEVELOPINGOTHERS = AttributesEnum.DevelopingOthers.index();
    public static final int LEADERSHIP = AttributesEnum.Leadership.index();
    public static final int INTEGRITY = AttributesEnum.Integrity.index();
    public static final int STABILITYUNDERPRESSURE = AttributesEnum.StabilityUnderPressure.index();
    public static final int ATTITUDETOWARDSAUTHORITY = AttributesEnum.AttitudeTowardsAuthority.index();
    public static final int LOYALTY = AttributesEnum.Loyalty.index();
    public static final int ABILITYTOLEARN = AttributesEnum.AbilityToLearn.index();
    public static final int ACCEPTINGCHANGE = AttributesEnum.AcceptingChange.index();
    public static final int FILLEDBYID = AttributesEnum.FilledById.index();
    public static final int FILLEDBYEMAIL = AttributesEnum.FilledByEmail.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int EMPNAME = AttributesEnum.EmpName.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int COACHESSTUFF = AttributesEnum.CoachesStuff.index();
    public static final int COMMSTYLEOHR = AttributesEnum.CommStyleOhr.index();
    public static final int COOPERATES = AttributesEnum.Cooperates.index();
    public static final int DELEGATESEFFECTIVALY = AttributesEnum.DelegatesEffectivaly.index();
    public static final int EASYTOWORK = AttributesEnum.EasyToWork.index();
    public static final int MOTIVATESFORMS = AttributesEnum.MotivatesForms.index();
    public static final int REMAINPOSITIVE = AttributesEnum.RemainPositive.index();
    public static final int REPECTFULPOLITEINCONVO = AttributesEnum.RepectfulPoliteInConvo.index();
    public static final int RESPONSIBLE = AttributesEnum.Responsible.index();
    public static final int SHARESINFO = AttributesEnum.SharesInfo.index();
    public static final int TAKETHINGPERSONALLY = AttributesEnum.TakeThingPersonally.index();
    public static final int GENERALCOMMENTS = AttributesEnum.GeneralComments.index();
    public static final int WORKACCURACY = AttributesEnum.WorkAccuracy.index();
    public static final int SUBMITIONDATE = AttributesEnum.SubmitionDate.index();
    public static final int ISSECURE = AttributesEnum.IsSecure.index();
    public static final int LINEMANAGERNAME = AttributesEnum.LineManagerName.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTE21 = AttributesEnum.Attribute21.index();
    public static final int ATTRIBUTE22 = AttributesEnum.Attribute22.index();
    public static final int ATTRIBUTE23 = AttributesEnum.Attribute23.index();
    public static final int ATTRIBUTE24 = AttributesEnum.Attribute24.index();
    public static final int ATTRIBUTE25 = AttributesEnum.Attribute25.index();
    public static final int ATTRIBUTE26 = AttributesEnum.Attribute26.index();
    public static final int ATTRIBUTE28 = AttributesEnum.Attribute28.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EO_XxEmpApFormImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("net.nishat.model.EO.EO_XxEmpApForm");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for EmpApFormId, using the alias name EmpApFormId.
     * @return the EmpApFormId
     */
    public Number getEmpApFormId() {
        return (Number)getAttributeInternal(EMPAPFORMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmpApFormId.
     * @param value value to set the EmpApFormId
     */
    public void setEmpApFormId(Number value) {
        setAttributeInternal(EMPAPFORMID, value);
    }

    /**
     * Gets the attribute value for DeptName, using the alias name DeptName.
     * @return the DeptName
     */
    public String getDeptName() {
        return (String)getAttributeInternal(DEPTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeptName.
     * @param value value to set the DeptName
     */
    public void setDeptName(String value) {
        setAttributeInternal(DEPTNAME, value);
    }


    /**
     * Gets the attribute value for EmpNo, using the alias name EmpNo.
     * @return the EmpNo
     */
    public String getEmpNo() {
        return (String)getAttributeInternal(EMPNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmpNo.
     * @param value value to set the EmpNo
     */
    public void setEmpNo(String value) {
        setAttributeInternal(EMPNO, value);
    }


    /**
     * Gets the attribute value for Qualification, using the alias name Qualification.
     * @return the Qualification
     */
    public String getQualification() {
        return (String)getAttributeInternal(QUALIFICATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Qualification.
     * @param value value to set the Qualification
     */
    public void setQualification(String value) {
        setAttributeInternal(QUALIFICATION, value);
    }

    /**
     * Gets the attribute value for Designation, using the alias name Designation.
     * @return the Designation
     */
    public String getDesignation() {
        return (String)getAttributeInternal(DESIGNATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Designation.
     * @param value value to set the Designation
     */
    public void setDesignation(String value) {
        setAttributeInternal(DESIGNATION, value);
    }

    /**
     * Gets the attribute value for Doj, using the alias name Doj.
     * @return the Doj
     */
    public Date getDoj() {
        return (Date)getAttributeInternal(DOJ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Doj.
     * @param value value to set the Doj
     */
    public void setDoj(Date value) {
        setAttributeInternal(DOJ, value);
    }

    /**
     * Gets the attribute value for LastPromotionOn, using the alias name LastPromotionOn.
     * @return the LastPromotionOn
     */
    public Date getLastPromotionOn() {
        return (Date)getAttributeInternal(LASTPROMOTIONON);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastPromotionOn.
     * @param value value to set the LastPromotionOn
     */
    public void setLastPromotionOn(Date value) {
        setAttributeInternal(LASTPROMOTIONON, value);
    }

    /**
     * Gets the attribute value for CommercialJudgment, using the alias name CommercialJudgment.
     * @return the CommercialJudgment
     */
    public String getCommercialJudgment() {
        return (String)getAttributeInternal(COMMERCIALJUDGMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommercialJudgment.
     * @param value value to set the CommercialJudgment
     */
    public void setCommercialJudgment(String value) {
        setAttributeInternal(COMMERCIALJUDGMENT, value);
    }

    /**
     * Gets the attribute value for ProductTechnicalKnowledge, using the alias name ProductTechnicalKnowledge.
     * @return the ProductTechnicalKnowledge
     */
    public String getProductTechnicalKnowledge() {
        return (String)getAttributeInternal(PRODUCTTECHNICALKNOWLEDGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductTechnicalKnowledge.
     * @param value value to set the ProductTechnicalKnowledge
     */
    public void setProductTechnicalKnowledge(String value) {
        setAttributeInternal(PRODUCTTECHNICALKNOWLEDGE, value);
    }

    /**
     * Gets the attribute value for TimeManagement, using the alias name TimeManagement.
     * @return the TimeManagement
     */
    public String getTimeManagement() {
        return (String)getAttributeInternal(TIMEMANAGEMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TimeManagement.
     * @param value value to set the TimeManagement
     */
    public void setTimeManagement(String value) {
        setAttributeInternal(TIMEMANAGEMENT, value);
    }

    /**
     * Gets the attribute value for CommunicationSkills, using the alias name CommunicationSkills.
     * @return the CommunicationSkills
     */
    public String getCommunicationSkills() {
        return (String)getAttributeInternal(COMMUNICATIONSKILLS);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommunicationSkills.
     * @param value value to set the CommunicationSkills
     */
    public void setCommunicationSkills(String value) {
        setAttributeInternal(COMMUNICATIONSKILLS, value);
    }

    /**
     * Gets the attribute value for DelegationSkills, using the alias name DelegationSkills.
     * @return the DelegationSkills
     */
    public String getDelegationSkills() {
        return (String)getAttributeInternal(DELEGATIONSKILLS);
    }

    /**
     * Sets <code>value</code> as the attribute value for DelegationSkills.
     * @param value value to set the DelegationSkills
     */
    public void setDelegationSkills(String value) {
        setAttributeInternal(DELEGATIONSKILLS, value);
    }

    /**
     * Gets the attribute value for MeetingDeadlines, using the alias name MeetingDeadlines.
     * @return the MeetingDeadlines
     */
    public String getMeetingDeadlines() {
        return (String)getAttributeInternal(MEETINGDEADLINES);
    }

    /**
     * Sets <code>value</code> as the attribute value for MeetingDeadlines.
     * @param value value to set the MeetingDeadlines
     */
    public void setMeetingDeadlines(String value) {
        setAttributeInternal(MEETINGDEADLINES, value);
    }

    /**
     * Gets the attribute value for CommitmentToWork, using the alias name CommitmentToWork.
     * @return the CommitmentToWork
     */
    public String getCommitmentToWork() {
        return (String)getAttributeInternal(COMMITMENTTOWORK);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommitmentToWork.
     * @param value value to set the CommitmentToWork
     */
    public void setCommitmentToWork(String value) {
        setAttributeInternal(COMMITMENTTOWORK, value);
    }

    /**
     * Gets the attribute value for Creativity, using the alias name Creativity.
     * @return the Creativity
     */
    public String getCreativity() {
        return (String)getAttributeInternal(CREATIVITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Creativity.
     * @param value value to set the Creativity
     */
    public void setCreativity(String value) {
        setAttributeInternal(CREATIVITY, value);
    }

    /**
     * Gets the attribute value for ProblemSolving, using the alias name ProblemSolving.
     * @return the ProblemSolving
     */
    public String getProblemSolving() {
        return (String)getAttributeInternal(PROBLEMSOLVING);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProblemSolving.
     * @param value value to set the ProblemSolving
     */
    public void setProblemSolving(String value) {
        setAttributeInternal(PROBLEMSOLVING, value);
    }

    /**
     * Gets the attribute value for TakingInitiative, using the alias name TakingInitiative.
     * @return the TakingInitiative
     */
    public String getTakingInitiative() {
        return (String)getAttributeInternal(TAKINGINITIATIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TakingInitiative.
     * @param value value to set the TakingInitiative
     */
    public void setTakingInitiative(String value) {
        setAttributeInternal(TAKINGINITIATIVE, value);
    }

    /**
     * Gets the attribute value for DecisionMaking, using the alias name DecisionMaking.
     * @return the DecisionMaking
     */
    public String getDecisionMaking() {
        return (String)getAttributeInternal(DECISIONMAKING);
    }

    /**
     * Sets <code>value</code> as the attribute value for DecisionMaking.
     * @param value value to set the DecisionMaking
     */
    public void setDecisionMaking(String value) {
        setAttributeInternal(DECISIONMAKING, value);
    }

    /**
     * Gets the attribute value for TeamWork, using the alias name TeamWork.
     * @return the TeamWork
     */
    public String getTeamWork() {
        return (String)getAttributeInternal(TEAMWORK);
    }

    /**
     * Sets <code>value</code> as the attribute value for TeamWork.
     * @param value value to set the TeamWork
     */
    public void setTeamWork(String value) {
        setAttributeInternal(TEAMWORK, value);
    }

    /**
     * Gets the attribute value for DevelopingOthers, using the alias name DevelopingOthers.
     * @return the DevelopingOthers
     */
    public String getDevelopingOthers() {
        return (String)getAttributeInternal(DEVELOPINGOTHERS);
    }

    /**
     * Sets <code>value</code> as the attribute value for DevelopingOthers.
     * @param value value to set the DevelopingOthers
     */
    public void setDevelopingOthers(String value) {
        setAttributeInternal(DEVELOPINGOTHERS, value);
    }

    /**
     * Gets the attribute value for Leadership, using the alias name Leadership.
     * @return the Leadership
     */
    public String getLeadership() {
        return (String)getAttributeInternal(LEADERSHIP);
    }

    /**
     * Sets <code>value</code> as the attribute value for Leadership.
     * @param value value to set the Leadership
     */
    public void setLeadership(String value) {
        setAttributeInternal(LEADERSHIP, value);
    }

    /**
     * Gets the attribute value for Integrity, using the alias name Integrity.
     * @return the Integrity
     */
    public String getIntegrity() {
        return (String)getAttributeInternal(INTEGRITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Integrity.
     * @param value value to set the Integrity
     */
    public void setIntegrity(String value) {
        setAttributeInternal(INTEGRITY, value);
    }

    /**
     * Gets the attribute value for StabilityUnderPressure, using the alias name StabilityUnderPressure.
     * @return the StabilityUnderPressure
     */
    public String getStabilityUnderPressure() {
        return (String)getAttributeInternal(STABILITYUNDERPRESSURE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StabilityUnderPressure.
     * @param value value to set the StabilityUnderPressure
     */
    public void setStabilityUnderPressure(String value) {
        setAttributeInternal(STABILITYUNDERPRESSURE, value);
    }

    /**
     * Gets the attribute value for AttitudeTowardsAuthority, using the alias name AttitudeTowardsAuthority.
     * @return the AttitudeTowardsAuthority
     */
    public String getAttitudeTowardsAuthority() {
        return (String)getAttributeInternal(ATTITUDETOWARDSAUTHORITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttitudeTowardsAuthority.
     * @param value value to set the AttitudeTowardsAuthority
     */
    public void setAttitudeTowardsAuthority(String value) {
        setAttributeInternal(ATTITUDETOWARDSAUTHORITY, value);
    }

    /**
     * Gets the attribute value for Loyalty, using the alias name Loyalty.
     * @return the Loyalty
     */
    public String getLoyalty() {
        return (String)getAttributeInternal(LOYALTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Loyalty.
     * @param value value to set the Loyalty
     */
    public void setLoyalty(String value) {
        setAttributeInternal(LOYALTY, value);
    }

    /**
     * Gets the attribute value for AbilityToLearn, using the alias name AbilityToLearn.
     * @return the AbilityToLearn
     */
    public String getAbilityToLearn() {
        return (String)getAttributeInternal(ABILITYTOLEARN);
    }

    /**
     * Sets <code>value</code> as the attribute value for AbilityToLearn.
     * @param value value to set the AbilityToLearn
     */
    public void setAbilityToLearn(String value) {
        setAttributeInternal(ABILITYTOLEARN, value);
    }

    /**
     * Gets the attribute value for AcceptingChange, using the alias name AcceptingChange.
     * @return the AcceptingChange
     */
    public String getAcceptingChange() {
        return (String)getAttributeInternal(ACCEPTINGCHANGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AcceptingChange.
     * @param value value to set the AcceptingChange
     */
    public void setAcceptingChange(String value) {
        setAttributeInternal(ACCEPTINGCHANGE, value);
    }

    /**
     * Gets the attribute value for FilledById, using the alias name FilledById.
     * @return the FilledById
     */
    public String getFilledById() {
        return (String)getAttributeInternal(FILLEDBYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FilledById.
     * @param value value to set the FilledById
     */
    public void setFilledById(String value) {
        setAttributeInternal(FILLEDBYID, value);
    }


    /**
     * Gets the attribute value for FilledByEmail, using the alias name FilledByEmail.
     * @return the FilledByEmail
     */
    public String getFilledByEmail() {
        return (String)getAttributeInternal(FILLEDBYEMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for FilledByEmail.
     * @param value value to set the FilledByEmail
     */
    public void setFilledByEmail(String value) {
        setAttributeInternal(FILLEDBYEMAIL, value);
    }

    /**
     * Gets the attribute value for Posted, using the alias name Posted.
     * @return the Posted
     */
    public String getPosted() {
        return (String)getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Posted.
     * @param value value to set the Posted
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for EmpName, using the alias name EmpName.
     * @return the EmpName
     */
    public String getEmpName() {
        return (String)getAttributeInternal(EMPNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmpName.
     * @param value value to set the EmpName
     */
    public void setEmpName(String value) {
        setAttributeInternal(EMPNAME, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for CoachesStuff, using the alias name CoachesStuff.
     * @return the CoachesStuff
     */
    public String getCoachesStuff() {
        return (String)getAttributeInternal(COACHESSTUFF);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoachesStuff.
     * @param value value to set the CoachesStuff
     */
    public void setCoachesStuff(String value) {
        setAttributeInternal(COACHESSTUFF, value);
    }

    /**
     * Gets the attribute value for CommStyleOhr, using the alias name CommStyleOhr.
     * @return the CommStyleOhr
     */
    public String getCommStyleOhr() {
        return (String)getAttributeInternal(COMMSTYLEOHR);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommStyleOhr.
     * @param value value to set the CommStyleOhr
     */
    public void setCommStyleOhr(String value) {
        setAttributeInternal(COMMSTYLEOHR, value);
    }

    /**
     * Gets the attribute value for Cooperates, using the alias name Cooperates.
     * @return the Cooperates
     */
    public String getCooperates() {
        return (String)getAttributeInternal(COOPERATES);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cooperates.
     * @param value value to set the Cooperates
     */
    public void setCooperates(String value) {
        setAttributeInternal(COOPERATES, value);
    }

    /**
     * Gets the attribute value for DelegatesEffectivaly, using the alias name DelegatesEffectivaly.
     * @return the DelegatesEffectivaly
     */
    public String getDelegatesEffectivaly() {
        return (String)getAttributeInternal(DELEGATESEFFECTIVALY);
    }

    /**
     * Sets <code>value</code> as the attribute value for DelegatesEffectivaly.
     * @param value value to set the DelegatesEffectivaly
     */
    public void setDelegatesEffectivaly(String value) {
        setAttributeInternal(DELEGATESEFFECTIVALY, value);
    }

    /**
     * Gets the attribute value for EasyToWork, using the alias name EasyToWork.
     * @return the EasyToWork
     */
    public String getEasyToWork() {
        return (String)getAttributeInternal(EASYTOWORK);
    }

    /**
     * Sets <code>value</code> as the attribute value for EasyToWork.
     * @param value value to set the EasyToWork
     */
    public void setEasyToWork(String value) {
        setAttributeInternal(EASYTOWORK, value);
    }


    /**
     * Gets the attribute value for MotivatesForms, using the alias name MotivatesForms.
     * @return the MotivatesForms
     */
    public String getMotivatesForms() {
        return (String)getAttributeInternal(MOTIVATESFORMS);
    }

    /**
     * Sets <code>value</code> as the attribute value for MotivatesForms.
     * @param value value to set the MotivatesForms
     */
    public void setMotivatesForms(String value) {
        setAttributeInternal(MOTIVATESFORMS, value);
    }

    /**
     * Gets the attribute value for RemainPositive, using the alias name RemainPositive.
     * @return the RemainPositive
     */
    public String getRemainPositive() {
        return (String)getAttributeInternal(REMAINPOSITIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RemainPositive.
     * @param value value to set the RemainPositive
     */
    public void setRemainPositive(String value) {
        setAttributeInternal(REMAINPOSITIVE, value);
    }

    /**
     * Gets the attribute value for RepectfulPoliteInConvo, using the alias name RepectfulPoliteInConvo.
     * @return the RepectfulPoliteInConvo
     */
    public String getRepectfulPoliteInConvo() {
        return (String)getAttributeInternal(REPECTFULPOLITEINCONVO);
    }

    /**
     * Sets <code>value</code> as the attribute value for RepectfulPoliteInConvo.
     * @param value value to set the RepectfulPoliteInConvo
     */
    public void setRepectfulPoliteInConvo(String value) {
        setAttributeInternal(REPECTFULPOLITEINCONVO, value);
    }

    /**
     * Gets the attribute value for Responsible, using the alias name Responsible.
     * @return the Responsible
     */
    public String getResponsible() {
        return (String)getAttributeInternal(RESPONSIBLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Responsible.
     * @param value value to set the Responsible
     */
    public void setResponsible(String value) {
        setAttributeInternal(RESPONSIBLE, value);
    }

    /**
     * Gets the attribute value for SharesInfo, using the alias name SharesInfo.
     * @return the SharesInfo
     */
    public String getSharesInfo() {
        return (String)getAttributeInternal(SHARESINFO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SharesInfo.
     * @param value value to set the SharesInfo
     */
    public void setSharesInfo(String value) {
        setAttributeInternal(SHARESINFO, value);
    }

    /**
     * Gets the attribute value for TakeThingPersonally, using the alias name TakeThingPersonally.
     * @return the TakeThingPersonally
     */
    public String getTakeThingPersonally() {
        return (String)getAttributeInternal(TAKETHINGPERSONALLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TakeThingPersonally.
     * @param value value to set the TakeThingPersonally
     */
    public void setTakeThingPersonally(String value) {
        setAttributeInternal(TAKETHINGPERSONALLY, value);
    }

    /**
     * Gets the attribute value for GeneralComments, using the alias name GeneralComments.
     * @return the GeneralComments
     */
    public String getGeneralComments() {
        return (String)getAttributeInternal(GENERALCOMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for GeneralComments.
     * @param value value to set the GeneralComments
     */
    public void setGeneralComments(String value) {
        setAttributeInternal(GENERALCOMMENTS, value);
    }

    /**
     * Gets the attribute value for WorkAccuracy, using the alias name WorkAccuracy.
     * @return the WorkAccuracy
     */
    public String getWorkAccuracy() {
        return (String)getAttributeInternal(WORKACCURACY);
    }

    /**
     * Sets <code>value</code> as the attribute value for WorkAccuracy.
     * @param value value to set the WorkAccuracy
     */
    public void setWorkAccuracy(String value) {
        setAttributeInternal(WORKACCURACY, value);
    }

    /**
     * Gets the attribute value for SubmitionDate, using the alias name SubmitionDate.
     * @return the SubmitionDate
     */
    public Date getSubmitionDate() {
        return (Date)getAttributeInternal(SUBMITIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubmitionDate.
     * @param value value to set the SubmitionDate
     */
    public void setSubmitionDate(Date value) {
        setAttributeInternal(SUBMITIONDATE, value);
    }

    /**
     * Gets the attribute value for IsSecure, using the alias name IsSecure.
     * @return the IsSecure
     */
    public Number getIsSecure() {
        return (Number)getAttributeInternal(ISSECURE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsSecure.
     * @param value value to set the IsSecure
     */
    public void setIsSecure(Number value) {
        setAttributeInternal(ISSECURE, value);
    }

    /**
     * Gets the attribute value for LineManagerName, using the alias name LineManagerName.
     * @return the LineManagerName
     */
    public String getLineManagerName() {
        return (String)getAttributeInternal(LINEMANAGERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineManagerName.
     * @param value value to set the LineManagerName
     */
    public void setLineManagerName(String value) {
        setAttributeInternal(LINEMANAGERNAME, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for Attribute16, using the alias name Attribute16.
     * @return the Attribute16
     */
    public String getAttribute16() {
        return (String)getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute16.
     * @param value value to set the Attribute16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for Attribute17, using the alias name Attribute17.
     * @return the Attribute17
     */
    public String getAttribute17() {
        return (String)getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute17.
     * @param value value to set the Attribute17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for Attribute18, using the alias name Attribute18.
     * @return the Attribute18
     */
    public String getAttribute18() {
        return (String)getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute18.
     * @param value value to set the Attribute18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for Attribute19, using the alias name Attribute19.
     * @return the Attribute19
     */
    public String getAttribute19() {
        return (String)getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute19.
     * @param value value to set the Attribute19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute20, using the alias name Attribute20.
     * @return the Attribute20
     */
    public String getAttribute20() {
        return (String)getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute20.
     * @param value value to set the Attribute20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for Attribute21, using the alias name Attribute21.
     * @return the Attribute21
     */
    public String getAttribute21() {
        return (String)getAttributeInternal(ATTRIBUTE21);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute21.
     * @param value value to set the Attribute21
     */
    public void setAttribute21(String value) {
        setAttributeInternal(ATTRIBUTE21, value);
    }

    /**
     * Gets the attribute value for Attribute22, using the alias name Attribute22.
     * @return the Attribute22
     */
    public String getAttribute22() {
        return (String)getAttributeInternal(ATTRIBUTE22);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute22.
     * @param value value to set the Attribute22
     */
    public void setAttribute22(String value) {
        setAttributeInternal(ATTRIBUTE22, value);
    }

    /**
     * Gets the attribute value for Attribute23, using the alias name Attribute23.
     * @return the Attribute23
     */
    public String getAttribute23() {
        return (String)getAttributeInternal(ATTRIBUTE23);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute23.
     * @param value value to set the Attribute23
     */
    public void setAttribute23(String value) {
        setAttributeInternal(ATTRIBUTE23, value);
    }

    /**
     * Gets the attribute value for Attribute24, using the alias name Attribute24.
     * @return the Attribute24
     */
    public String getAttribute24() {
        return (String)getAttributeInternal(ATTRIBUTE24);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute24.
     * @param value value to set the Attribute24
     */
    public void setAttribute24(String value) {
        setAttributeInternal(ATTRIBUTE24, value);
    }

    /**
     * Gets the attribute value for Attribute25, using the alias name Attribute25.
     * @return the Attribute25
     */
    public String getAttribute25() {
        return (String)getAttributeInternal(ATTRIBUTE25);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute25.
     * @param value value to set the Attribute25
     */
    public void setAttribute25(String value) {
        setAttributeInternal(ATTRIBUTE25, value);
    }

    /**
     * Gets the attribute value for Attribute26, using the alias name Attribute26.
     * @return the Attribute26
     */
    public String getAttribute26() {
        return (String)getAttributeInternal(ATTRIBUTE26);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute26.
     * @param value value to set the Attribute26
     */
    public void setAttribute26(String value) {
        setAttributeInternal(ATTRIBUTE26, value);
    }

    /**
     * Gets the attribute value for Attribute28, using the alias name Attribute28.
     * @return the Attribute28
     */
    public String getAttribute28() {
        return (String)getAttributeInternal(ATTRIBUTE28);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute28.
     * @param value value to set the Attribute28
     */
    public void setAttribute28(String value) {
        setAttributeInternal(ATTRIBUTE28, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param empApFormId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number empApFormId) {
        return new Key(new Object[]{empApFormId});
    }


}
