package net.nishat.model.EO;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 18 18:34:37 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EO_XXSubOrdFormV2Impl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        FormId {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getFormId();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setFormId((Number)value);
            }
        }
        ,
        EmployeeDepartment {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getEmployeeDepartment();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setEmployeeDepartment((String)value);
            }
        }
        ,
        LineManagerName {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getLineManagerName();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setLineManagerName((String)value);
            }
        }
        ,
        EmployeeNo {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getEmployeeNo();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setEmployeeNo((String)value);
            }
        }
        ,
        EmployeeName {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getEmployeeName();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setEmployeeName((String)value);
            }
        }
        ,
        EmpQualification {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getEmpQualification();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setEmpQualification((String)value);
            }
        }
        ,
        EmpDesignation {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getEmpDesignation();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setEmpDesignation((String)value);
            }
        }
        ,
        EmpDoj {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getEmpDoj();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setEmpDoj((Date)value);
            }
        }
        ,
        Attribute1 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute1();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute2();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute3();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute4();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute5();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute6();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute7();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute8();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute9();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute10();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute11();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute12();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute13();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute14();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute15();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute16 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute16();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute16((String)value);
            }
        }
        ,
        Attribute17 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute17();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute17((String)value);
            }
        }
        ,
        Attribute18 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute18();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute18((String)value);
            }
        }
        ,
        Attribute19 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute19();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute19((String)value);
            }
        }
        ,
        Attribute20 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute20();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute20((String)value);
            }
        }
        ,
        Attribute21 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute21();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute21((String)value);
            }
        }
        ,
        Attribute22 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute22();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute22((String)value);
            }
        }
        ,
        Attribute23 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute23();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute23((String)value);
            }
        }
        ,
        Attribute24 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute24();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute24((String)value);
            }
        }
        ,
        Attribute25 {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getAttribute25();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setAttribute25((String)value);
            }
        }
        ,
        LastPromotionDate {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getLastPromotionDate();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setLastPromotionDate((Date)value);
            }
        }
        ,
        HodRemarks {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getHodRemarks();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setHodRemarks((String)value);
            }
        }
        ,
        LineManagerId {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getLineManagerId();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setLineManagerId((String)value);
            }
        }
        ,
        Posted {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getPosted();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setPosted((String)value);
            }
        }
        ,
        SubmitionDate {
            public Object get(EO_XXSubOrdFormV2Impl obj) {
                return obj.getSubmitionDate();
            }

            public void put(EO_XXSubOrdFormV2Impl obj, Object value) {
                obj.setSubmitionDate((Date)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(EO_XXSubOrdFormV2Impl object);

        public abstract void put(EO_XXSubOrdFormV2Impl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int FORMID = AttributesEnum.FormId.index();
    public static final int EMPLOYEEDEPARTMENT = AttributesEnum.EmployeeDepartment.index();
    public static final int LINEMANAGERNAME = AttributesEnum.LineManagerName.index();
    public static final int EMPLOYEENO = AttributesEnum.EmployeeNo.index();
    public static final int EMPLOYEENAME = AttributesEnum.EmployeeName.index();
    public static final int EMPQUALIFICATION = AttributesEnum.EmpQualification.index();
    public static final int EMPDESIGNATION = AttributesEnum.EmpDesignation.index();
    public static final int EMPDOJ = AttributesEnum.EmpDoj.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTE21 = AttributesEnum.Attribute21.index();
    public static final int ATTRIBUTE22 = AttributesEnum.Attribute22.index();
    public static final int ATTRIBUTE23 = AttributesEnum.Attribute23.index();
    public static final int ATTRIBUTE24 = AttributesEnum.Attribute24.index();
    public static final int ATTRIBUTE25 = AttributesEnum.Attribute25.index();
    public static final int LASTPROMOTIONDATE = AttributesEnum.LastPromotionDate.index();
    public static final int HODREMARKS = AttributesEnum.HodRemarks.index();
    public static final int LINEMANAGERID = AttributesEnum.LineManagerId.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int SUBMITIONDATE = AttributesEnum.SubmitionDate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EO_XXSubOrdFormV2Impl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("net.nishat.model.EO.EO_XXSubOrdFormV2");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for FormId, using the alias name FormId.
     * @return the FormId
     */
    public Number getFormId() {
        return (Number)getAttributeInternal(FORMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FormId.
     * @param value value to set the FormId
     */
    public void setFormId(Number value) {
        setAttributeInternal(FORMID, value);
    }

    /**
     * Gets the attribute value for EmployeeDepartment, using the alias name EmployeeDepartment.
     * @return the EmployeeDepartment
     */
    public String getEmployeeDepartment() {
        return (String)getAttributeInternal(EMPLOYEEDEPARTMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeDepartment.
     * @param value value to set the EmployeeDepartment
     */
    public void setEmployeeDepartment(String value) {
        setAttributeInternal(EMPLOYEEDEPARTMENT, value);
    }

    /**
     * Gets the attribute value for LineManagerName, using the alias name LineManagerName.
     * @return the LineManagerName
     */
    public String getLineManagerName() {
        return (String)getAttributeInternal(LINEMANAGERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineManagerName.
     * @param value value to set the LineManagerName
     */
    public void setLineManagerName(String value) {
        setAttributeInternal(LINEMANAGERNAME, value);
    }

    /**
     * Gets the attribute value for EmployeeNo, using the alias name EmployeeNo.
     * @return the EmployeeNo
     */
    public String getEmployeeNo() {
        return (String)getAttributeInternal(EMPLOYEENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeNo.
     * @param value value to set the EmployeeNo
     */
    public void setEmployeeNo(String value) {
        setAttributeInternal(EMPLOYEENO, value);
    }

    /**
     * Gets the attribute value for EmployeeName, using the alias name EmployeeName.
     * @return the EmployeeName
     */
    public String getEmployeeName() {
        return (String)getAttributeInternal(EMPLOYEENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeName.
     * @param value value to set the EmployeeName
     */
    public void setEmployeeName(String value) {
        setAttributeInternal(EMPLOYEENAME, value);
    }

    /**
     * Gets the attribute value for EmpQualification, using the alias name EmpQualification.
     * @return the EmpQualification
     */
    public String getEmpQualification() {
        return (String)getAttributeInternal(EMPQUALIFICATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmpQualification.
     * @param value value to set the EmpQualification
     */
    public void setEmpQualification(String value) {
        setAttributeInternal(EMPQUALIFICATION, value);
    }

    /**
     * Gets the attribute value for EmpDesignation, using the alias name EmpDesignation.
     * @return the EmpDesignation
     */
    public String getEmpDesignation() {
        return (String)getAttributeInternal(EMPDESIGNATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmpDesignation.
     * @param value value to set the EmpDesignation
     */
    public void setEmpDesignation(String value) {
        setAttributeInternal(EMPDESIGNATION, value);
    }

    /**
     * Gets the attribute value for EmpDoj, using the alias name EmpDoj.
     * @return the EmpDoj
     */
    public Date getEmpDoj() {
        return (Date)getAttributeInternal(EMPDOJ);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmpDoj.
     * @param value value to set the EmpDoj
     */
    public void setEmpDoj(Date value) {
        setAttributeInternal(EMPDOJ, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for Attribute16, using the alias name Attribute16.
     * @return the Attribute16
     */
    public String getAttribute16() {
        return (String)getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute16.
     * @param value value to set the Attribute16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for Attribute17, using the alias name Attribute17.
     * @return the Attribute17
     */
    public String getAttribute17() {
        return (String)getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute17.
     * @param value value to set the Attribute17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for Attribute18, using the alias name Attribute18.
     * @return the Attribute18
     */
    public String getAttribute18() {
        return (String)getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute18.
     * @param value value to set the Attribute18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for Attribute19, using the alias name Attribute19.
     * @return the Attribute19
     */
    public String getAttribute19() {
        return (String)getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute19.
     * @param value value to set the Attribute19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for Attribute20, using the alias name Attribute20.
     * @return the Attribute20
     */
    public String getAttribute20() {
        return (String)getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute20.
     * @param value value to set the Attribute20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for Attribute21, using the alias name Attribute21.
     * @return the Attribute21
     */
    public String getAttribute21() {
        return (String)getAttributeInternal(ATTRIBUTE21);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute21.
     * @param value value to set the Attribute21
     */
    public void setAttribute21(String value) {
        setAttributeInternal(ATTRIBUTE21, value);
    }

    /**
     * Gets the attribute value for Attribute22, using the alias name Attribute22.
     * @return the Attribute22
     */
    public String getAttribute22() {
        return (String)getAttributeInternal(ATTRIBUTE22);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute22.
     * @param value value to set the Attribute22
     */
    public void setAttribute22(String value) {
        setAttributeInternal(ATTRIBUTE22, value);
    }

    /**
     * Gets the attribute value for Attribute23, using the alias name Attribute23.
     * @return the Attribute23
     */
    public String getAttribute23() {
        return (String)getAttributeInternal(ATTRIBUTE23);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute23.
     * @param value value to set the Attribute23
     */
    public void setAttribute23(String value) {
        setAttributeInternal(ATTRIBUTE23, value);
    }

    /**
     * Gets the attribute value for Attribute24, using the alias name Attribute24.
     * @return the Attribute24
     */
    public String getAttribute24() {
        return (String)getAttributeInternal(ATTRIBUTE24);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute24.
     * @param value value to set the Attribute24
     */
    public void setAttribute24(String value) {
        setAttributeInternal(ATTRIBUTE24, value);
    }

    /**
     * Gets the attribute value for Attribute25, using the alias name Attribute25.
     * @return the Attribute25
     */
    public String getAttribute25() {
        return (String)getAttributeInternal(ATTRIBUTE25);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute25.
     * @param value value to set the Attribute25
     */
    public void setAttribute25(String value) {
        setAttributeInternal(ATTRIBUTE25, value);
    }

    /**
     * Gets the attribute value for LastPromotionDate, using the alias name LastPromotionDate.
     * @return the LastPromotionDate
     */
    public Date getLastPromotionDate() {
        return (Date)getAttributeInternal(LASTPROMOTIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastPromotionDate.
     * @param value value to set the LastPromotionDate
     */
    public void setLastPromotionDate(Date value) {
        setAttributeInternal(LASTPROMOTIONDATE, value);
    }

    /**
     * Gets the attribute value for HodRemarks, using the alias name HodRemarks.
     * @return the HodRemarks
     */
    public String getHodRemarks() {
        return (String)getAttributeInternal(HODREMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for HodRemarks.
     * @param value value to set the HodRemarks
     */
    public void setHodRemarks(String value) {
        setAttributeInternal(HODREMARKS, value);
    }

    /**
     * Gets the attribute value for LineManagerId, using the alias name LineManagerId.
     * @return the LineManagerId
     */
    public String getLineManagerId() {
        return (String)getAttributeInternal(LINEMANAGERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineManagerId.
     * @param value value to set the LineManagerId
     */
    public void setLineManagerId(String value) {
        setAttributeInternal(LINEMANAGERID, value);
    }

    /**
     * Gets the attribute value for Posted, using the alias name Posted.
     * @return the Posted
     */
    public String getPosted() {
        return (String)getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Posted.
     * @param value value to set the Posted
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for SubmitionDate, using the alias name SubmitionDate.
     * @return the SubmitionDate
     */
    public Date getSubmitionDate() {
        return (Date)getAttributeInternal(SUBMITIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubmitionDate.
     * @param value value to set the SubmitionDate
     */
    public void setSubmitionDate(Date value) {
        setAttributeInternal(SUBMITIONDATE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param formId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number formId) {
        return new Key(new Object[]{formId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        this.setFormId(new SequenceImpl("xx_emp_ap_form_seq",
                                                   getDBTransaction()).getSequenceNumber());
    }


}
