package net.nishat.model.AM.client;

import net.nishat.model.AM.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 25 11:33:42 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }


    public void refreshEmpFormData() {
        Object _ret =
            this.riInvokeExportedMethod(this,"refreshEmpFormData",null,null);
        return;
    }

    public void refreshSubordFormData() {
        Object _ret =
            this.riInvokeExportedMethod(this,"refreshSubordFormData",null,null);
        return;
    }

    public void refreshPeerFormData() {
        Object _ret =
            this.riInvokeExportedMethod(this,"refreshPeerFormData",null,null);
        return;
    }
}
