package net.nishat.model.VO;

import javax.faces.context.FacesContext;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 17 16:16:50 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_ViewFormsImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VO_ViewFormsImpl() {
    }

    /**
     * Returns the bind variable value for hod_dpt.
     * @return bind variable value for hod_dpt
     */
    public String gethod_dpt() {
        FacesContext fctx = FacesContext.getCurrentInstance();
        HttpServletRequest req =
            (HttpServletRequest)fctx.getExternalContext().getRequest();
        HttpSession session = req.getSession();
        
        return (String)session.getAttribute("user_dpt");
    }

    /**
     * Sets <code>value</code> for bind variable hod_dpt.
     * @param value value to bind as hod_dpt
     */
    public void sethod_dpt(String value) {
        setNamedWhereClauseParam("hod_dpt", value);
    }

    /**
     * Returns the variable value for emp_name.
     * @return variable value for emp_name
     */
    public String getemp_name() {
        return (String)ensureVariableManager().getVariableValue("emp_name");
    }

    /**
     * Sets <code>value</code> for variable emp_name.
     * @param value value to bind as emp_name
     */
    public void setemp_name(String value) {
        ensureVariableManager().setVariableValue("emp_name", value);
    }
}
