package net.nishat.model.VO;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;



import javax.faces.context.FacesContext;

import javax.servlet.http.HttpServletRequest;

import javax.servlet.http.HttpSession;

import net.nishat.model.EO.EO_XxEmpApFormImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 16 09:22:56 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_XxEmpApFormRowImpl extends ViewRowImpl {
    @Override
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        FacesContext fctx = FacesContext.getCurrentInstance();
        HttpServletRequest req =
            (HttpServletRequest)fctx.getExternalContext().getRequest();
        HttpSession session = req.getSession();
        this.setFilledById((String)session.getAttribute("user_id"));
        this.setFilledByEmail((String)session.getAttribute("user_email"));
        this.setEmpName((String)session.getAttribute("user_name"));
        this.setDesignation((String)session.getAttribute("user_des"));
//        this.setDeptName((String)session.getAttribute("user_dpt"));
        System.out.println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"+(String)session.getAttribute("user_dpt"));
        this.setDeptName(""+(String)session.getAttribute("user_dpt"));
        this.setEmpNo((String)session.getAttribute("user_no"));
        this.setLineManagerName((String)session.getAttribute("user_parent_name"));
        
        //this.setPosted("NO");
        //this.setDoj(castToJBODate((String)session.getAttribute("user_doj")));   
    }

    public oracle.jbo.domain.Date castToJBODate(String aDate){
              DateFormat formatter;
              java.util.Date date;
     
              if(aDate!=null){
     
                try {
     
                  formatter = new SimpleDateFormat("MM/DD/yyyy");
                  date = formatter.parse(aDate);
                  java.sql.Date sqlDate = new java.sql.Date(date.getTime());
                  oracle.jbo.domain.Date jboDate = new oracle.jbo.domain.Date(sqlDate);
     
                    return jboDate;
                } catch (ParseException e) {
                            e.printStackTrace();
                    }
     
             }
     
             return null;
    }

    

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        EmpApFormId {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getEmpApFormId();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setEmpApFormId((Number)value);
            }
        }
        ,
        DeptName {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getDeptName();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setDeptName((String)value);
            }
        }
        ,
        EmpNo {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getEmpNo();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setEmpNo((String)value);
            }
        }
        ,
        Qualification {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getQualification();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setQualification((String)value);
            }
        }
        ,
        Designation {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getDesignation();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setDesignation((String)value);
            }
        }
        ,
        Doj {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getDoj();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setDoj((Date)value);
            }
        }
        ,
        LastPromotionOn {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getLastPromotionOn();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setLastPromotionOn((Date)value);
            }
        }
        ,
        CommercialJudgment {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getCommercialJudgment();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setCommercialJudgment((String)value);
            }
        }
        ,
        ProductTechnicalKnowledge {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getProductTechnicalKnowledge();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setProductTechnicalKnowledge((String)value);
            }
        }
        ,
        TimeManagement {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getTimeManagement();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setTimeManagement((String)value);
            }
        }
        ,
        CommunicationSkills {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getCommunicationSkills();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setCommunicationSkills((String)value);
            }
        }
        ,
        DelegationSkills {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getDelegationSkills();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setDelegationSkills((String)value);
            }
        }
        ,
        MeetingDeadlines {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getMeetingDeadlines();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setMeetingDeadlines((String)value);
            }
        }
        ,
        CommitmentToWork {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getCommitmentToWork();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setCommitmentToWork((String)value);
            }
        }
        ,
        Creativity {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getCreativity();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setCreativity((String)value);
            }
        }
        ,
        ProblemSolving {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getProblemSolving();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setProblemSolving((String)value);
            }
        }
        ,
        TakingInitiative {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getTakingInitiative();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setTakingInitiative((String)value);
            }
        }
        ,
        DecisionMaking {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getDecisionMaking();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setDecisionMaking((String)value);
            }
        }
        ,
        TeamWork {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getTeamWork();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setTeamWork((String)value);
            }
        }
        ,
        DevelopingOthers {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getDevelopingOthers();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setDevelopingOthers((String)value);
            }
        }
        ,
        Leadership {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getLeadership();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setLeadership((String)value);
            }
        }
        ,
        Integrity {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getIntegrity();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setIntegrity((String)value);
            }
        }
        ,
        StabilityUnderPressure {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getStabilityUnderPressure();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setStabilityUnderPressure((String)value);
            }
        }
        ,
        AttitudeTowardsAuthority {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttitudeTowardsAuthority();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttitudeTowardsAuthority((String)value);
            }
        }
        ,
        Loyalty {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getLoyalty();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setLoyalty((String)value);
            }
        }
        ,
        AbilityToLearn {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAbilityToLearn();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAbilityToLearn((String)value);
            }
        }
        ,
        AcceptingChange {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAcceptingChange();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAcceptingChange((String)value);
            }
        }
        ,
        FilledById {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getFilledById();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setFilledById((String)value);
            }
        }
        ,
        FilledByEmail {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getFilledByEmail();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setFilledByEmail((String)value);
            }
        }
        ,
        Posted {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getPosted();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setPosted((String)value);
            }
        }
        ,
        Remarks {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getRemarks();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        CommStyleOhr {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getCommStyleOhr();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setCommStyleOhr((String)value);
            }
        }
        ,
        TakeThingPersonally {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getTakeThingPersonally();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setTakeThingPersonally((String)value);
            }
        }
        ,
        RemainPositive {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getRemainPositive();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setRemainPositive((String)value);
            }
        }
        ,
        CoachesStuff {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getCoachesStuff();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setCoachesStuff((String)value);
            }
        }
        ,
        MotivatesForms {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getMotivatesForms();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setMotivatesForms((String)value);
            }
        }
        ,
        DelegatesEffectivaly {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getDelegatesEffectivaly();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setDelegatesEffectivaly((String)value);
            }
        }
        ,
        RepectfulPoliteInConvo {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getRepectfulPoliteInConvo();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setRepectfulPoliteInConvo((String)value);
            }
        }
        ,
        EasyToWork {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getEasyToWork();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setEasyToWork((String)value);
            }
        }
        ,
        Responsible {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getResponsible();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setResponsible((String)value);
            }
        }
        ,
        Cooperates {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getCooperates();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setCooperates((String)value);
            }
        }
        ,
        SharesInfo {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getSharesInfo();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setSharesInfo((String)value);
            }
        }
        ,
        GeneralComments {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getGeneralComments();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setGeneralComments((String)value);
            }
        }
        ,
        WorkAccuracy {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getWorkAccuracy();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setWorkAccuracy((String)value);
            }
        }
        ,
        EmpName {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getEmpName();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setEmpName((String)value);
            }
        }
        ,
        SubmitionDate {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getSubmitionDate();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setSubmitionDate((Date)value);
            }
        }
        ,
        IsSecure {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getIsSecure();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setIsSecure((Number)value);
            }
        }
        ,
        LineManagerName {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getLineManagerName();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setLineManagerName((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute16 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute16();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute16((String)value);
            }
        }
        ,
        Attribute17 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute17();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute17((String)value);
            }
        }
        ,
        Attribute18 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute18();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute18((String)value);
            }
        }
        ,
        Attribute19 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute19();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute19((String)value);
            }
        }
        ,
        Attribute20 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute20();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute20((String)value);
            }
        }
        ,
        Attribute21 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute21();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute21((String)value);
            }
        }
        ,
        Attribute22 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute22();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute22((String)value);
            }
        }
        ,
        Attribute23 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute23();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute23((String)value);
            }
        }
        ,
        Attribute24 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute24();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute24((String)value);
            }
        }
        ,
        Attribute25 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute25();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute25((String)value);
            }
        }
        ,
        Attribute26 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getAttribute26();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttribute26((String)value);
            }
        }
        ,
        posted_boolean {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getposted_boolean();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setposted_boolean((Boolean)value);
            }
        }
        ,
        VO_AllEmployeeSearch1 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getVO_AllEmployeeSearch1();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        VO_LovGradingScaleForSubordinate1 {
            public Object get(VO_XxEmpApFormRowImpl obj) {
                return obj.getVO_LovGradingScaleForSubordinate1();
            }

            public void put(VO_XxEmpApFormRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(VO_XxEmpApFormRowImpl object);

        public abstract void put(VO_XxEmpApFormRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EMPAPFORMID = AttributesEnum.EmpApFormId.index();
    public static final int DEPTNAME = AttributesEnum.DeptName.index();
    public static final int EMPNO = AttributesEnum.EmpNo.index();
    public static final int QUALIFICATION = AttributesEnum.Qualification.index();
    public static final int DESIGNATION = AttributesEnum.Designation.index();
    public static final int DOJ = AttributesEnum.Doj.index();
    public static final int LASTPROMOTIONON = AttributesEnum.LastPromotionOn.index();
    public static final int COMMERCIALJUDGMENT = AttributesEnum.CommercialJudgment.index();
    public static final int PRODUCTTECHNICALKNOWLEDGE = AttributesEnum.ProductTechnicalKnowledge.index();
    public static final int TIMEMANAGEMENT = AttributesEnum.TimeManagement.index();
    public static final int COMMUNICATIONSKILLS = AttributesEnum.CommunicationSkills.index();
    public static final int DELEGATIONSKILLS = AttributesEnum.DelegationSkills.index();
    public static final int MEETINGDEADLINES = AttributesEnum.MeetingDeadlines.index();
    public static final int COMMITMENTTOWORK = AttributesEnum.CommitmentToWork.index();
    public static final int CREATIVITY = AttributesEnum.Creativity.index();
    public static final int PROBLEMSOLVING = AttributesEnum.ProblemSolving.index();
    public static final int TAKINGINITIATIVE = AttributesEnum.TakingInitiative.index();
    public static final int DECISIONMAKING = AttributesEnum.DecisionMaking.index();
    public static final int TEAMWORK = AttributesEnum.TeamWork.index();
    public static final int DEVELOPINGOTHERS = AttributesEnum.DevelopingOthers.index();
    public static final int LEADERSHIP = AttributesEnum.Leadership.index();
    public static final int INTEGRITY = AttributesEnum.Integrity.index();
    public static final int STABILITYUNDERPRESSURE = AttributesEnum.StabilityUnderPressure.index();
    public static final int ATTITUDETOWARDSAUTHORITY = AttributesEnum.AttitudeTowardsAuthority.index();
    public static final int LOYALTY = AttributesEnum.Loyalty.index();
    public static final int ABILITYTOLEARN = AttributesEnum.AbilityToLearn.index();
    public static final int ACCEPTINGCHANGE = AttributesEnum.AcceptingChange.index();
    public static final int FILLEDBYID = AttributesEnum.FilledById.index();
    public static final int FILLEDBYEMAIL = AttributesEnum.FilledByEmail.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int COMMSTYLEOHR = AttributesEnum.CommStyleOhr.index();
    public static final int TAKETHINGPERSONALLY = AttributesEnum.TakeThingPersonally.index();
    public static final int REMAINPOSITIVE = AttributesEnum.RemainPositive.index();
    public static final int COACHESSTUFF = AttributesEnum.CoachesStuff.index();
    public static final int MOTIVATESFORMS = AttributesEnum.MotivatesForms.index();
    public static final int DELEGATESEFFECTIVALY = AttributesEnum.DelegatesEffectivaly.index();
    public static final int REPECTFULPOLITEINCONVO = AttributesEnum.RepectfulPoliteInConvo.index();
    public static final int EASYTOWORK = AttributesEnum.EasyToWork.index();
    public static final int RESPONSIBLE = AttributesEnum.Responsible.index();
    public static final int COOPERATES = AttributesEnum.Cooperates.index();
    public static final int SHARESINFO = AttributesEnum.SharesInfo.index();
    public static final int GENERALCOMMENTS = AttributesEnum.GeneralComments.index();
    public static final int WORKACCURACY = AttributesEnum.WorkAccuracy.index();
    public static final int EMPNAME = AttributesEnum.EmpName.index();
    public static final int SUBMITIONDATE = AttributesEnum.SubmitionDate.index();
    public static final int ISSECURE = AttributesEnum.IsSecure.index();
    public static final int LINEMANAGERNAME = AttributesEnum.LineManagerName.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTE21 = AttributesEnum.Attribute21.index();
    public static final int ATTRIBUTE22 = AttributesEnum.Attribute22.index();
    public static final int ATTRIBUTE23 = AttributesEnum.Attribute23.index();
    public static final int ATTRIBUTE24 = AttributesEnum.Attribute24.index();
    public static final int ATTRIBUTE25 = AttributesEnum.Attribute25.index();
    public static final int ATTRIBUTE26 = AttributesEnum.Attribute26.index();
    public static final int POSTED_BOOLEAN = AttributesEnum.posted_boolean.index();
    public static final int VO_ALLEMPLOYEESEARCH1 = AttributesEnum.VO_AllEmployeeSearch1.index();
    public static final int VO_LOVGRADINGSCALEFORSUBORDINATE1 = AttributesEnum.VO_LovGradingScaleForSubordinate1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VO_XxEmpApFormRowImpl() {
    }

    /**
     * Gets EO_XxEmpApForm entity object.
     * @return the EO_XxEmpApForm
     */
    public EO_XxEmpApFormImpl getEO_XxEmpApForm() {
        return (EO_XxEmpApFormImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for EMP_AP_FORM_ID using the alias name EmpApFormId.
     * @return the EMP_AP_FORM_ID
     */
    public Number getEmpApFormId() {
        return (Number)getAttributeInternal(EMPAPFORMID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_AP_FORM_ID using the alias name EmpApFormId.
     * @param value value to set the EMP_AP_FORM_ID
     */
    public void setEmpApFormId(Number value) {
        setAttributeInternal(EMPAPFORMID, value);
    }

    /**
     * Gets the attribute value for DEPT_NAME using the alias name DeptName.
     * @return the DEPT_NAME
     */
    public String getDeptName() {
        return (String)getAttributeInternal(DEPTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPT_NAME using the alias name DeptName.
     * @param value value to set the DEPT_NAME
     */
    public void setDeptName(String value) {
        setAttributeInternal(DEPTNAME, value);
    }


    /**
     * Gets the attribute value for EMP_NO using the alias name EmpNo.
     * @return the EMP_NO
     */
    public String getEmpNo() {
        return (String)getAttributeInternal(EMPNO);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_NO using the alias name EmpNo.
     * @param value value to set the EMP_NO
     */
    public void setEmpNo(String value) {
        setAttributeInternal(EMPNO, value);
    }


    /**
     * Gets the attribute value for QUALIFICATION using the alias name Qualification.
     * @return the QUALIFICATION
     */
    public String getQualification() {
        return (String)getAttributeInternal(QUALIFICATION);
    }

    /**
     * Sets <code>value</code> as attribute value for QUALIFICATION using the alias name Qualification.
     * @param value value to set the QUALIFICATION
     */
    public void setQualification(String value) {
        setAttributeInternal(QUALIFICATION, value);
    }

    /**
     * Gets the attribute value for DESIGNATION using the alias name Designation.
     * @return the DESIGNATION
     */
    public String getDesignation() {
        return (String)getAttributeInternal(DESIGNATION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESIGNATION using the alias name Designation.
     * @param value value to set the DESIGNATION
     */
    public void setDesignation(String value) {
        setAttributeInternal(DESIGNATION, value);
    }

    /**
     * Gets the attribute value for DOJ using the alias name Doj.
     * @return the DOJ
     */
    public Date getDoj() {
        return (Date)getAttributeInternal(DOJ);
    }

    /**
     * Sets <code>value</code> as attribute value for DOJ using the alias name Doj.
     * @param value value to set the DOJ
     */
    public void setDoj(Date value) {
        setAttributeInternal(DOJ, value);
    }

    /**
     * Gets the attribute value for LAST_PROMOTION_ON using the alias name LastPromotionOn.
     * @return the LAST_PROMOTION_ON
     */
    public Date getLastPromotionOn() {
        return (Date)getAttributeInternal(LASTPROMOTIONON);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_PROMOTION_ON using the alias name LastPromotionOn.
     * @param value value to set the LAST_PROMOTION_ON
     */
    public void setLastPromotionOn(Date value) {
        setAttributeInternal(LASTPROMOTIONON, value);
    }

    /**
     * Gets the attribute value for COMMERCIAL_JUDGMENT using the alias name CommercialJudgment.
     * @return the COMMERCIAL_JUDGMENT
     */
    public String getCommercialJudgment() {
        return (String)getAttributeInternal(COMMERCIALJUDGMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMERCIAL_JUDGMENT using the alias name CommercialJudgment.
     * @param value value to set the COMMERCIAL_JUDGMENT
     */
    public void setCommercialJudgment(String value) {
        setAttributeInternal(COMMERCIALJUDGMENT, value);
    }

    /**
     * Gets the attribute value for PRODUCT_TECHNICAL_KNOWLEDGE using the alias name ProductTechnicalKnowledge.
     * @return the PRODUCT_TECHNICAL_KNOWLEDGE
     */
    public String getProductTechnicalKnowledge() {
        return (String)getAttributeInternal(PRODUCTTECHNICALKNOWLEDGE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_TECHNICAL_KNOWLEDGE using the alias name ProductTechnicalKnowledge.
     * @param value value to set the PRODUCT_TECHNICAL_KNOWLEDGE
     */
    public void setProductTechnicalKnowledge(String value) {
        setAttributeInternal(PRODUCTTECHNICALKNOWLEDGE, value);
    }

    /**
     * Gets the attribute value for TIME_MANAGEMENT using the alias name TimeManagement.
     * @return the TIME_MANAGEMENT
     */
    public String getTimeManagement() {
        return (String)getAttributeInternal(TIMEMANAGEMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for TIME_MANAGEMENT using the alias name TimeManagement.
     * @param value value to set the TIME_MANAGEMENT
     */
    public void setTimeManagement(String value) {
        setAttributeInternal(TIMEMANAGEMENT, value);
    }

    /**
     * Gets the attribute value for COMMUNICATION_SKILLS using the alias name CommunicationSkills.
     * @return the COMMUNICATION_SKILLS
     */
    public String getCommunicationSkills() {
        return (String)getAttributeInternal(COMMUNICATIONSKILLS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMUNICATION_SKILLS using the alias name CommunicationSkills.
     * @param value value to set the COMMUNICATION_SKILLS
     */
    public void setCommunicationSkills(String value) {
        setAttributeInternal(COMMUNICATIONSKILLS, value);
    }

    /**
     * Gets the attribute value for DELEGATION_SKILLS using the alias name DelegationSkills.
     * @return the DELEGATION_SKILLS
     */
    public String getDelegationSkills() {
        return (String)getAttributeInternal(DELEGATIONSKILLS);
    }

    /**
     * Sets <code>value</code> as attribute value for DELEGATION_SKILLS using the alias name DelegationSkills.
     * @param value value to set the DELEGATION_SKILLS
     */
    public void setDelegationSkills(String value) {
        setAttributeInternal(DELEGATIONSKILLS, value);
    }

    /**
     * Gets the attribute value for MEETING_DEADLINES using the alias name MeetingDeadlines.
     * @return the MEETING_DEADLINES
     */
    public String getMeetingDeadlines() {
        return (String)getAttributeInternal(MEETINGDEADLINES);
    }

    /**
     * Sets <code>value</code> as attribute value for MEETING_DEADLINES using the alias name MeetingDeadlines.
     * @param value value to set the MEETING_DEADLINES
     */
    public void setMeetingDeadlines(String value) {
        setAttributeInternal(MEETINGDEADLINES, value);
    }

    /**
     * Gets the attribute value for COMMITMENT_TO_WORK using the alias name CommitmentToWork.
     * @return the COMMITMENT_TO_WORK
     */
    public String getCommitmentToWork() {
        return (String)getAttributeInternal(COMMITMENTTOWORK);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMITMENT_TO_WORK using the alias name CommitmentToWork.
     * @param value value to set the COMMITMENT_TO_WORK
     */
    public void setCommitmentToWork(String value) {
        setAttributeInternal(COMMITMENTTOWORK, value);
    }

    /**
     * Gets the attribute value for CREATIVITY using the alias name Creativity.
     * @return the CREATIVITY
     */
    public String getCreativity() {
        return (String)getAttributeInternal(CREATIVITY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATIVITY using the alias name Creativity.
     * @param value value to set the CREATIVITY
     */
    public void setCreativity(String value) {
        setAttributeInternal(CREATIVITY, value);
    }

    /**
     * Gets the attribute value for PROBLEM_SOLVING using the alias name ProblemSolving.
     * @return the PROBLEM_SOLVING
     */
    public String getProblemSolving() {
        return (String)getAttributeInternal(PROBLEMSOLVING);
    }

    /**
     * Sets <code>value</code> as attribute value for PROBLEM_SOLVING using the alias name ProblemSolving.
     * @param value value to set the PROBLEM_SOLVING
     */
    public void setProblemSolving(String value) {
        setAttributeInternal(PROBLEMSOLVING, value);
    }

    /**
     * Gets the attribute value for TAKING_INITIATIVE using the alias name TakingInitiative.
     * @return the TAKING_INITIATIVE
     */
    public String getTakingInitiative() {
        return (String)getAttributeInternal(TAKINGINITIATIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for TAKING_INITIATIVE using the alias name TakingInitiative.
     * @param value value to set the TAKING_INITIATIVE
     */
    public void setTakingInitiative(String value) {
        setAttributeInternal(TAKINGINITIATIVE, value);
    }

    /**
     * Gets the attribute value for DECISION_MAKING using the alias name DecisionMaking.
     * @return the DECISION_MAKING
     */
    public String getDecisionMaking() {
        return (String)getAttributeInternal(DECISIONMAKING);
    }

    /**
     * Sets <code>value</code> as attribute value for DECISION_MAKING using the alias name DecisionMaking.
     * @param value value to set the DECISION_MAKING
     */
    public void setDecisionMaking(String value) {
        setAttributeInternal(DECISIONMAKING, value);
    }

    /**
     * Gets the attribute value for TEAM_WORK using the alias name TeamWork.
     * @return the TEAM_WORK
     */
    public String getTeamWork() {
        return (String)getAttributeInternal(TEAMWORK);
    }

    /**
     * Sets <code>value</code> as attribute value for TEAM_WORK using the alias name TeamWork.
     * @param value value to set the TEAM_WORK
     */
    public void setTeamWork(String value) {
        setAttributeInternal(TEAMWORK, value);
    }

    /**
     * Gets the attribute value for DEVELOPING_OTHERS using the alias name DevelopingOthers.
     * @return the DEVELOPING_OTHERS
     */
    public String getDevelopingOthers() {
        return (String)getAttributeInternal(DEVELOPINGOTHERS);
    }

    /**
     * Sets <code>value</code> as attribute value for DEVELOPING_OTHERS using the alias name DevelopingOthers.
     * @param value value to set the DEVELOPING_OTHERS
     */
    public void setDevelopingOthers(String value) {
        setAttributeInternal(DEVELOPINGOTHERS, value);
    }

    /**
     * Gets the attribute value for LEADERSHIP using the alias name Leadership.
     * @return the LEADERSHIP
     */
    public String getLeadership() {
        return (String)getAttributeInternal(LEADERSHIP);
    }

    /**
     * Sets <code>value</code> as attribute value for LEADERSHIP using the alias name Leadership.
     * @param value value to set the LEADERSHIP
     */
    public void setLeadership(String value) {
        setAttributeInternal(LEADERSHIP, value);
    }

    /**
     * Gets the attribute value for INTEGRITY using the alias name Integrity.
     * @return the INTEGRITY
     */
    public String getIntegrity() {
        return (String)getAttributeInternal(INTEGRITY);
    }

    /**
     * Sets <code>value</code> as attribute value for INTEGRITY using the alias name Integrity.
     * @param value value to set the INTEGRITY
     */
    public void setIntegrity(String value) {
        setAttributeInternal(INTEGRITY, value);
    }

    /**
     * Gets the attribute value for STABILITY_UNDER_PRESSURE using the alias name StabilityUnderPressure.
     * @return the STABILITY_UNDER_PRESSURE
     */
    public String getStabilityUnderPressure() {
        return (String)getAttributeInternal(STABILITYUNDERPRESSURE);
    }

    /**
     * Sets <code>value</code> as attribute value for STABILITY_UNDER_PRESSURE using the alias name StabilityUnderPressure.
     * @param value value to set the STABILITY_UNDER_PRESSURE
     */
    public void setStabilityUnderPressure(String value) {
        setAttributeInternal(STABILITYUNDERPRESSURE, value);
    }

    /**
     * Gets the attribute value for ATTITUDE_TOWARDS_AUTHORITY using the alias name AttitudeTowardsAuthority.
     * @return the ATTITUDE_TOWARDS_AUTHORITY
     */
    public String getAttitudeTowardsAuthority() {
        return (String)getAttributeInternal(ATTITUDETOWARDSAUTHORITY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTITUDE_TOWARDS_AUTHORITY using the alias name AttitudeTowardsAuthority.
     * @param value value to set the ATTITUDE_TOWARDS_AUTHORITY
     */
    public void setAttitudeTowardsAuthority(String value) {
        setAttributeInternal(ATTITUDETOWARDSAUTHORITY, value);
    }

    /**
     * Gets the attribute value for LOYALTY using the alias name Loyalty.
     * @return the LOYALTY
     */
    public String getLoyalty() {
        return (String)getAttributeInternal(LOYALTY);
    }

    /**
     * Sets <code>value</code> as attribute value for LOYALTY using the alias name Loyalty.
     * @param value value to set the LOYALTY
     */
    public void setLoyalty(String value) {
        setAttributeInternal(LOYALTY, value);
    }

    /**
     * Gets the attribute value for ABILITY_TO_LEARN using the alias name AbilityToLearn.
     * @return the ABILITY_TO_LEARN
     */
    public String getAbilityToLearn() {
        return (String)getAttributeInternal(ABILITYTOLEARN);
    }

    /**
     * Sets <code>value</code> as attribute value for ABILITY_TO_LEARN using the alias name AbilityToLearn.
     * @param value value to set the ABILITY_TO_LEARN
     */
    public void setAbilityToLearn(String value) {
        setAttributeInternal(ABILITYTOLEARN, value);
    }

    /**
     * Gets the attribute value for ACCEPTING_CHANGE using the alias name AcceptingChange.
     * @return the ACCEPTING_CHANGE
     */
    public String getAcceptingChange() {
        return (String)getAttributeInternal(ACCEPTINGCHANGE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCEPTING_CHANGE using the alias name AcceptingChange.
     * @param value value to set the ACCEPTING_CHANGE
     */
    public void setAcceptingChange(String value) {
        setAttributeInternal(ACCEPTINGCHANGE, value);
    }

    /**
     * Gets the attribute value for FILLED_BY_ID using the alias name FilledById.
     * @return the FILLED_BY_ID
     */
    public String getFilledById() {
        return (String)getAttributeInternal(FILLEDBYID);
    }

    /**
     * Sets <code>value</code> as attribute value for FILLED_BY_ID using the alias name FilledById.
     * @param value value to set the FILLED_BY_ID
     */
    public void setFilledById(String value) {
        setAttributeInternal(FILLEDBYID, value);
    }


    /**
     * Gets the attribute value for FILLED_BY_EMAIL using the alias name FilledByEmail.
     * @return the FILLED_BY_EMAIL
     */
    public String getFilledByEmail() {
        return (String)getAttributeInternal(FILLEDBYEMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for FILLED_BY_EMAIL using the alias name FilledByEmail.
     * @param value value to set the FILLED_BY_EMAIL
     */
    public void setFilledByEmail(String value) {
        setAttributeInternal(FILLEDBYEMAIL, value);
    }

    /**
     * Gets the attribute value for POSTED using the alias name Posted.
     * @return the POSTED
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTED using the alias name Posted.
     * @param value value to set the POSTED
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }


    /**
     * Gets the attribute value for the calculated attribute posted_boolean.
     * @return the posted_boolean
     */
    public Boolean getposted_boolean() {
        boolean b = false;
        if (getPosted() == null) {
            b = false;
        }else if (getPosted().equals("YES")) {
            b = true;
        }
        return b;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute posted_boolean.
     * @param value value to set the  posted_boolean
     */
    public void setposted_boolean(Boolean value) {
        if (value) {
            this.setPosted("YES");
        }else{
            this.setPosted(null);
        }
    }

    /**
     * Gets the attribute value for SUBMITION_DATE using the alias name SubmitionDate.
     * @return the SUBMITION_DATE
     */
    public Date getSubmitionDate() {
        return (Date) getAttributeInternal(SUBMITIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMITION_DATE using the alias name SubmitionDate.
     * @param value value to set the SUBMITION_DATE
     */
    public void setSubmitionDate(Date value) {
        setAttributeInternal(SUBMITIONDATE, value);
    }

    /**
     * Gets the attribute value for IS_SECURE using the alias name IsSecure.
     * @return the IS_SECURE
     */
    public Number getIsSecure() {
        return (Number) getAttributeInternal(ISSECURE);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_SECURE using the alias name IsSecure.
     * @param value value to set the IS_SECURE
     */
    public void setIsSecure(Number value) {
        setAttributeInternal(ISSECURE, value);
    }

    /**
     * Gets the attribute value for LINE_MANAGER_NAME using the alias name LineManagerName.
     * @return the LINE_MANAGER_NAME
     */
    public String getLineManagerName() {
        return (String) getAttributeInternal(LINEMANAGERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_MANAGER_NAME using the alias name LineManagerName.
     * @param value value to set the LINE_MANAGER_NAME
     */
    public void setLineManagerName(String value) {
        setAttributeInternal(LINEMANAGERNAME, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @return the ATTRIBUTE16
     */
    public String getAttribute16() {
        return (String) getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @param value value to set the ATTRIBUTE16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @return the ATTRIBUTE17
     */
    public String getAttribute17() {
        return (String) getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @param value value to set the ATTRIBUTE17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @return the ATTRIBUTE18
     */
    public String getAttribute18() {
        return (String) getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @param value value to set the ATTRIBUTE18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @return the ATTRIBUTE19
     */
    public String getAttribute19() {
        return (String) getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @param value value to set the ATTRIBUTE19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @return the ATTRIBUTE20
     */
    public String getAttribute20() {
        return (String) getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @param value value to set the ATTRIBUTE20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE21 using the alias name Attribute21.
     * @return the ATTRIBUTE21
     */
    public String getAttribute21() {
        return (String) getAttributeInternal(ATTRIBUTE21);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE21 using the alias name Attribute21.
     * @param value value to set the ATTRIBUTE21
     */
    public void setAttribute21(String value) {
        setAttributeInternal(ATTRIBUTE21, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE22 using the alias name Attribute22.
     * @return the ATTRIBUTE22
     */
    public String getAttribute22() {
        return (String) getAttributeInternal(ATTRIBUTE22);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE22 using the alias name Attribute22.
     * @param value value to set the ATTRIBUTE22
     */
    public void setAttribute22(String value) {
        setAttributeInternal(ATTRIBUTE22, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE23 using the alias name Attribute23.
     * @return the ATTRIBUTE23
     */
    public String getAttribute23() {
        return (String) getAttributeInternal(ATTRIBUTE23);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE23 using the alias name Attribute23.
     * @param value value to set the ATTRIBUTE23
     */
    public void setAttribute23(String value) {
        setAttributeInternal(ATTRIBUTE23, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE24 using the alias name Attribute24.
     * @return the ATTRIBUTE24
     */
    public String getAttribute24() {
        return (String) getAttributeInternal(ATTRIBUTE24);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE24 using the alias name Attribute24.
     * @param value value to set the ATTRIBUTE24
     */
    public void setAttribute24(String value) {
        setAttributeInternal(ATTRIBUTE24, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE25 using the alias name Attribute25.
     * @return the ATTRIBUTE25
     */
    public String getAttribute25() {
        return (String) getAttributeInternal(ATTRIBUTE25);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE25 using the alias name Attribute25.
     * @param value value to set the ATTRIBUTE25
     */
    public void setAttribute25(String value) {
        setAttributeInternal(ATTRIBUTE25, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE26 using the alias name Attribute26.
     * @return the ATTRIBUTE26
     */
    public String getAttribute26() {
        return (String) getAttributeInternal(ATTRIBUTE26);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE26 using the alias name Attribute26.
     * @param value value to set the ATTRIBUTE26
     */
    public void setAttribute26(String value) {
        setAttributeInternal(ATTRIBUTE26, value);
    }


    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_AllEmployeeSearch1.
     */
    public RowSet getVO_AllEmployeeSearch1() {
        return (RowSet)getAttributeInternal(VO_ALLEMPLOYEESEARCH1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_LovGradingScaleForSubordinate1.
     */
    public RowSet getVO_LovGradingScaleForSubordinate1() {
        return (RowSet)getAttributeInternal(VO_LOVGRADINGSCALEFORSUBORDINATE1);
    }

    /**
     * Gets the attribute value for WORK_ACCURACY using the alias name WorkAccuracy.
     * @return the WORK_ACCURACY
     */
    public String getWorkAccuracy() {
        return (String) getAttributeInternal(WORKACCURACY);
    }

    /**
     * Sets <code>value</code> as attribute value for WORK_ACCURACY using the alias name WorkAccuracy.
     * @param value value to set the WORK_ACCURACY
     */
    public void setWorkAccuracy(String value) {
        setAttributeInternal(WORKACCURACY, value);
    }

    /**
     * Gets the attribute value for GENERAL_COMMENTS using the alias name GeneralComments.
     * @return the GENERAL_COMMENTS
     */
    public String getGeneralComments() {
        return (String) getAttributeInternal(GENERALCOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for GENERAL_COMMENTS using the alias name GeneralComments.
     * @param value value to set the GENERAL_COMMENTS
     */
    public void setGeneralComments(String value) {
        setAttributeInternal(GENERALCOMMENTS, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }


    /**
     * Gets the attribute value for EMP_NAME using the alias name EmpName.
     * @return the EMP_NAME
     */
    public String getEmpName() {
        return (String) getAttributeInternal(EMPNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_NAME using the alias name EmpName.
     * @param value value to set the EMP_NAME
     */
    public void setEmpName(String value) {
        setAttributeInternal(EMPNAME, value);
    }

    /**
     * Gets the attribute value for COMM_STYLE_OHR using the alias name CommStyleOhr.
     * @return the COMM_STYLE_OHR
     */
    public String getCommStyleOhr() {
        return (String) getAttributeInternal(COMMSTYLEOHR);
    }

    /**
     * Sets <code>value</code> as attribute value for COMM_STYLE_OHR using the alias name CommStyleOhr.
     * @param value value to set the COMM_STYLE_OHR
     */
    public void setCommStyleOhr(String value) {
        setAttributeInternal(COMMSTYLEOHR, value);
    }

    /**
     * Gets the attribute value for TAKE_THING_PERSONALLY using the alias name TakeThingPersonally.
     * @return the TAKE_THING_PERSONALLY
     */
    public String getTakeThingPersonally() {
        return (String) getAttributeInternal(TAKETHINGPERSONALLY);
    }

    /**
     * Sets <code>value</code> as attribute value for TAKE_THING_PERSONALLY using the alias name TakeThingPersonally.
     * @param value value to set the TAKE_THING_PERSONALLY
     */
    public void setTakeThingPersonally(String value) {
        setAttributeInternal(TAKETHINGPERSONALLY, value);
    }

    /**
     * Gets the attribute value for REMAIN_POSITIVE using the alias name RemainPositive.
     * @return the REMAIN_POSITIVE
     */
    public String getRemainPositive() {
        return (String) getAttributeInternal(REMAINPOSITIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for REMAIN_POSITIVE using the alias name RemainPositive.
     * @param value value to set the REMAIN_POSITIVE
     */
    public void setRemainPositive(String value) {
        setAttributeInternal(REMAINPOSITIVE, value);
    }

    /**
     * Gets the attribute value for COACHES_STUFF using the alias name CoachesStuff.
     * @return the COACHES_STUFF
     */
    public String getCoachesStuff() {
        return (String) getAttributeInternal(COACHESSTUFF);
    }

    /**
     * Sets <code>value</code> as attribute value for COACHES_STUFF using the alias name CoachesStuff.
     * @param value value to set the COACHES_STUFF
     */
    public void setCoachesStuff(String value) {
        setAttributeInternal(COACHESSTUFF, value);
    }

    /**
     * Gets the attribute value for MOTIVATES_FORMS using the alias name MotivatesForms.
     * @return the MOTIVATES_FORMS
     */
    public String getMotivatesForms() {
        return (String) getAttributeInternal(MOTIVATESFORMS);
    }

    /**
     * Sets <code>value</code> as attribute value for MOTIVATES_FORMS using the alias name MotivatesForms.
     * @param value value to set the MOTIVATES_FORMS
     */
    public void setMotivatesForms(String value) {
        setAttributeInternal(MOTIVATESFORMS, value);
    }

    /**
     * Gets the attribute value for DELEGATES_EFFECTIVALY using the alias name DelegatesEffectivaly.
     * @return the DELEGATES_EFFECTIVALY
     */
    public String getDelegatesEffectivaly() {
        return (String) getAttributeInternal(DELEGATESEFFECTIVALY);
    }

    /**
     * Sets <code>value</code> as attribute value for DELEGATES_EFFECTIVALY using the alias name DelegatesEffectivaly.
     * @param value value to set the DELEGATES_EFFECTIVALY
     */
    public void setDelegatesEffectivaly(String value) {
        setAttributeInternal(DELEGATESEFFECTIVALY, value);
    }


    /**
     * Gets the attribute value for REPECTFUL_POLITE_IN_CONVO using the alias name RepectfulPoliteInConvo.
     * @return the REPECTFUL_POLITE_IN_CONVO
     */
    public String getRepectfulPoliteInConvo() {
        return (String) getAttributeInternal(REPECTFULPOLITEINCONVO);
    }

    /**
     * Sets <code>value</code> as attribute value for REPECTFUL_POLITE_IN_CONVO using the alias name RepectfulPoliteInConvo.
     * @param value value to set the REPECTFUL_POLITE_IN_CONVO
     */
    public void setRepectfulPoliteInConvo(String value) {
        setAttributeInternal(REPECTFULPOLITEINCONVO, value);
    }

    /**
     * Gets the attribute value for EASY_TO_WORK using the alias name EasyToWork.
     * @return the EASY_TO_WORK
     */
    public String getEasyToWork() {
        return (String) getAttributeInternal(EASYTOWORK);
    }

    /**
     * Sets <code>value</code> as attribute value for EASY_TO_WORK using the alias name EasyToWork.
     * @param value value to set the EASY_TO_WORK
     */
    public void setEasyToWork(String value) {
        setAttributeInternal(EASYTOWORK, value);
    }

    /**
     * Gets the attribute value for RESPONSIBLE using the alias name Responsible.
     * @return the RESPONSIBLE
     */
    public String getResponsible() {
        return (String) getAttributeInternal(RESPONSIBLE);
    }

    /**
     * Sets <code>value</code> as attribute value for RESPONSIBLE using the alias name Responsible.
     * @param value value to set the RESPONSIBLE
     */
    public void setResponsible(String value) {
        setAttributeInternal(RESPONSIBLE, value);
    }

    /**
     * Gets the attribute value for COOPERATES using the alias name Cooperates.
     * @return the COOPERATES
     */
    public String getCooperates() {
        return (String) getAttributeInternal(COOPERATES);
    }

    /**
     * Sets <code>value</code> as attribute value for COOPERATES using the alias name Cooperates.
     * @param value value to set the COOPERATES
     */
    public void setCooperates(String value) {
        setAttributeInternal(COOPERATES, value);
    }

    /**
     * Gets the attribute value for SHARES_INFO using the alias name SharesInfo.
     * @return the SHARES_INFO
     */
    public String getSharesInfo() {
        return (String) getAttributeInternal(SHARESINFO);
    }

    /**
     * Sets <code>value</code> as attribute value for SHARES_INFO using the alias name SharesInfo.
     * @param value value to set the SHARES_INFO
     */
    public void setSharesInfo(String value) {
        setAttributeInternal(SHARESINFO, value);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
