package net.nishat.model.VO;

import javax.faces.context.FacesContext;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 17 11:22:25 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_XXSubOrdFormImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VO_XXSubOrdFormImpl() {
    }

    /**
     * Returns the bind variable value for emp_id.
     * @return bind variable value for emp_id
     */
    public String getemp_id() {
        FacesContext fctx = FacesContext.getCurrentInstance();
        HttpServletRequest req =
            (HttpServletRequest)fctx.getExternalContext().getRequest();
        HttpSession session = req.getSession();
        String userid = ((String)session.getAttribute("user_id"));
        System.out.println("VO_XxSubOrdForm:" + userid);
        if (userid == null) {
            return "";
        }else{
            return userid.trim();
        }
    }

    /**
     * Sets <code>value</code> for bind variable emp_id.
     * @param value value to bind as emp_id
     */
    public void setemp_id(String value) {
        setNamedWhereClauseParam("emp_id", value);
    }

    /**
     * Returns the variable value for subordinate_name.
     * @return variable value for subordinate_name
     */
    public String getsubordinate_name() {
        return (String)ensureVariableManager().getVariableValue("subordinate_name");
    }

    /**
     * Sets <code>value</code> for variable subordinate_name.
     * @param value value to bind as subordinate_name
     */
    public void setsubordinate_name(String value) {
        ensureVariableManager().setVariableValue("subordinate_name", value);
    }
}
