package net.nishat.model.VO;

import javax.faces.context.FacesContext;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 19 13:22:49 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_XXSubOrdFormV2Impl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VO_XXSubOrdFormV2Impl() {
    }

    /**
     * Returns the variable value for employee_name.
     * @return variable value for employee_name
     */
    public String getemployee_name() {
        return (String)ensureVariableManager().getVariableValue("employee_name");
    }

    /**
     * Sets <code>value</code> for variable employee_name.
     * @param value value to bind as employee_name
     */
    public void setemployee_name(String value) {
        ensureVariableManager().setVariableValue("employee_name", value);
    }

    /**
     * Returns the bind variable value for emp_id.
     * @return bind variable value for emp_id
     */
    public String getemp_id() {
     //   return (String)getNamedWhereClauseParam("emp_id");
     FacesContext fctx = FacesContext.getCurrentInstance();
     HttpServletRequest req =
         (HttpServletRequest)fctx.getExternalContext().getRequest();
     HttpSession session = req.getSession();
     String userid = ((String)session.getAttribute("user_id"));
     System.out.println("VO_XxSubOrdForm:" + userid);
     if (userid == null) {
         return "";
     }else{
         return userid.trim();
     }
    }

    /**
     * Sets <code>value</code> for bind variable emp_id.
     * @param value value to bind as emp_id
     */
    public void setemp_id(String value) {
        setNamedWhereClauseParam("emp_id", value);
    }
}
