package net.nishat.model.VO;

import javax.faces.context.FacesContext;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 15 12:47:46 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_XxLmApFormViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VO_XxLmApFormViewImpl() {
    }

    /**
     * Returns the bind variable value for user_id.
     * @return bind variable value for user_id
     */
    public String getuser_id() {
        FacesContext fctx = FacesContext.getCurrentInstance();
        HttpServletRequest req =
            (HttpServletRequest)fctx.getExternalContext().getRequest();
        HttpSession session = req.getSession();
        
        return (String)session.getAttribute("user_id");
    }

    /**
     * Sets <code>value</code> for bind variable user_id.
     * @param value value to bind as user_id
     */
    public void setuser_id(String value) {
        setNamedWhereClauseParam("user_id", value);
    }
}
