package net.nishat.model.VO;

import java.sql.ResultSet;

import javax.faces.context.FacesContext;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 16 09:22:56 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_XxEmpApFormImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VO_XxEmpApFormImpl() {
    }

    /**
     * executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object[] params,
                                             int noUserParams) {
        super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**
     * hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**
     * createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc,
                                                 ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**
     * getQueryHitCount - overridden for custom java data source support.
     */
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }


    /**
     * Returns the bind variable value for user_id.
     * @return bind variable value for user_id
     */
    public String getuser_id() {
        FacesContext fctx = FacesContext.getCurrentInstance();
        HttpServletRequest req =
            (HttpServletRequest)fctx.getExternalContext().getRequest();
        HttpSession session = req.getSession();
        String userid = ((String)session.getAttribute("user_id"));
        if (userid == null) {
            return "";
        }else if (userid.equals("3220")) {
            
            //return "the_key";
        
        return userid;
        }else{
            return userid;
        }
    }

    /**
     * Sets <code>value</code> for bind variable user_id.
     * @param value value to bind as user_id
     */
    public void setuser_id(String value) {
        setNamedWhereClauseParam("user_id", value);
    }

    /**
     * Returns the variable value for vcb_dpt_name.
     * @return variable value for vcb_dpt_name
     */
    public String getvcb_dpt_name() {
        return (String)ensureVariableManager().getVariableValue("vcb_dpt_name");
    }

    /**
     * Sets <code>value</code> for variable vcb_dpt_name.
     * @param value value to bind as vcb_dpt_name
     */
    public void setvcb_dpt_name(String value) {
        ensureVariableManager().setVariableValue("vcb_dpt_name", value);
    }
}
