package net.nishat.model.VO;

import javax.faces.context.FacesContext;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import net.nishat.model.EO.EO_XXSubOrdFormImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 17 11:02:38 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_XXSubOrdFormRowImpl extends ViewRowImpl {
    @Override
    protected void create(AttributeList attributeList) {
        FacesContext fctx = FacesContext.getCurrentInstance();
        HttpServletRequest req =
            (HttpServletRequest)fctx.getExternalContext().getRequest();
        HttpSession session = req.getSession();
        this.setLineManagerName((String)session.getAttribute("user_name"));
        this.setLineManagerId((String)session.getAttribute("user_id"));
        super.create(attributeList);
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        FormId {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getFormId();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setFormId((Number)value);
            }
        }
        ,
        EmployeeDepartment {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getEmployeeDepartment();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setEmployeeDepartment((String)value);
            }
        }
        ,
        LineManagerName {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getLineManagerName();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setLineManagerName((String)value);
            }
        }
        ,
        EmployeeNo {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getEmployeeNo();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setEmployeeNo((String)value);
            }
        }
        ,
        EmployeeName {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getEmployeeName();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setEmployeeName((String)value);
            }
        }
        ,
        EmpQualification {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getEmpQualification();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setEmpQualification((String)value);
            }
        }
        ,
        EmpDesignation {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getEmpDesignation();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setEmpDesignation((String)value);
            }
        }
        ,
        EmpDoj {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getEmpDoj();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setEmpDoj((Date)value);
            }
        }
        ,
        LastPromotionDate {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getLastPromotionDate();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setLastPromotionDate((Date)value);
            }
        }
        ,
        CommercialJudgment {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getCommercialJudgment();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setCommercialJudgment((String)value);
            }
        }
        ,
        ProductTechnicalKnowledge {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getProductTechnicalKnowledge();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setProductTechnicalKnowledge((String)value);
            }
        }
        ,
        TimeManagement {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getTimeManagement();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setTimeManagement((String)value);
            }
        }
        ,
        CommunicationSkills {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getCommunicationSkills();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setCommunicationSkills((String)value);
            }
        }
        ,
        DelegationSkills {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getDelegationSkills();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setDelegationSkills((String)value);
            }
        }
        ,
        MeetingDeadlines {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getMeetingDeadlines();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setMeetingDeadlines((String)value);
            }
        }
        ,
        CommitmentToWork {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getCommitmentToWork();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setCommitmentToWork((String)value);
            }
        }
        ,
        Creativity {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getCreativity();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setCreativity((String)value);
            }
        }
        ,
        ProblemSolving {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getProblemSolving();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setProblemSolving((String)value);
            }
        }
        ,
        TakingInitiative {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getTakingInitiative();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setTakingInitiative((String)value);
            }
        }
        ,
        DecisionMaking {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getDecisionMaking();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setDecisionMaking((String)value);
            }
        }
        ,
        TeamWork {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getTeamWork();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setTeamWork((String)value);
            }
        }
        ,
        DevelopingOthers {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getDevelopingOthers();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setDevelopingOthers((String)value);
            }
        }
        ,
        Leadership {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getLeadership();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setLeadership((String)value);
            }
        }
        ,
        Integrity {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getIntegrity();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setIntegrity((String)value);
            }
        }
        ,
        StabilityUnderPressure {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getStabilityUnderPressure();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setStabilityUnderPressure((String)value);
            }
        }
        ,
        AttitudeTowardsAuthority {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getAttitudeTowardsAuthority();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setAttitudeTowardsAuthority((String)value);
            }
        }
        ,
        Loyalty {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getLoyalty();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setLoyalty((String)value);
            }
        }
        ,
        AbilityToLearn {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getAbilityToLearn();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setAbilityToLearn((String)value);
            }
        }
        ,
        AcceptingChange {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getAcceptingChange();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setAcceptingChange((String)value);
            }
        }
        ,
        PRepectfulPoliteInConvo {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getPRepectfulPoliteInConvo();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setPRepectfulPoliteInConvo((String)value);
            }
        }
        ,
        PEasyToWork {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getPEasyToWork();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setPEasyToWork((String)value);
            }
        }
        ,
        PResponsible {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getPResponsible();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setPResponsible((String)value);
            }
        }
        ,
        PCooperates {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getPCooperates();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setPCooperates((String)value);
            }
        }
        ,
        PSharesInfo {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getPSharesInfo();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setPSharesInfo((String)value);
            }
        }
        ,
        LineManagerId {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getLineManagerId();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setLineManagerId((String)value);
            }
        }
        ,
        Posted {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getPosted();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setPosted((String)value);
            }
        }
        ,
        PGeneralCommentsPeers {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getPGeneralCommentsPeers();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setPGeneralCommentsPeers((String)value);
            }
        }
        ,
        HodRemarks {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getHodRemarks();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setHodRemarks((String)value);
            }
        }
        ,
        SubmitionDate {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getSubmitionDate();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setSubmitionDate((Date)value);
            }
        }
        ,
        posted_boolean {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getposted_boolean();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setposted_boolean((Boolean)value);
            }
        }
        ,
        VO_SearchEmployee1 {
            public Object get(VO_XXSubOrdFormRowImpl obj) {
                return obj.getVO_SearchEmployee1();
            }

            public void put(VO_XXSubOrdFormRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(VO_XXSubOrdFormRowImpl object);

        public abstract void put(VO_XXSubOrdFormRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int FORMID = AttributesEnum.FormId.index();
    public static final int EMPLOYEEDEPARTMENT = AttributesEnum.EmployeeDepartment.index();
    public static final int LINEMANAGERNAME = AttributesEnum.LineManagerName.index();
    public static final int EMPLOYEENO = AttributesEnum.EmployeeNo.index();
    public static final int EMPLOYEENAME = AttributesEnum.EmployeeName.index();
    public static final int EMPQUALIFICATION = AttributesEnum.EmpQualification.index();
    public static final int EMPDESIGNATION = AttributesEnum.EmpDesignation.index();
    public static final int EMPDOJ = AttributesEnum.EmpDoj.index();
    public static final int LASTPROMOTIONDATE = AttributesEnum.LastPromotionDate.index();
    public static final int COMMERCIALJUDGMENT = AttributesEnum.CommercialJudgment.index();
    public static final int PRODUCTTECHNICALKNOWLEDGE = AttributesEnum.ProductTechnicalKnowledge.index();
    public static final int TIMEMANAGEMENT = AttributesEnum.TimeManagement.index();
    public static final int COMMUNICATIONSKILLS = AttributesEnum.CommunicationSkills.index();
    public static final int DELEGATIONSKILLS = AttributesEnum.DelegationSkills.index();
    public static final int MEETINGDEADLINES = AttributesEnum.MeetingDeadlines.index();
    public static final int COMMITMENTTOWORK = AttributesEnum.CommitmentToWork.index();
    public static final int CREATIVITY = AttributesEnum.Creativity.index();
    public static final int PROBLEMSOLVING = AttributesEnum.ProblemSolving.index();
    public static final int TAKINGINITIATIVE = AttributesEnum.TakingInitiative.index();
    public static final int DECISIONMAKING = AttributesEnum.DecisionMaking.index();
    public static final int TEAMWORK = AttributesEnum.TeamWork.index();
    public static final int DEVELOPINGOTHERS = AttributesEnum.DevelopingOthers.index();
    public static final int LEADERSHIP = AttributesEnum.Leadership.index();
    public static final int INTEGRITY = AttributesEnum.Integrity.index();
    public static final int STABILITYUNDERPRESSURE = AttributesEnum.StabilityUnderPressure.index();
    public static final int ATTITUDETOWARDSAUTHORITY = AttributesEnum.AttitudeTowardsAuthority.index();
    public static final int LOYALTY = AttributesEnum.Loyalty.index();
    public static final int ABILITYTOLEARN = AttributesEnum.AbilityToLearn.index();
    public static final int ACCEPTINGCHANGE = AttributesEnum.AcceptingChange.index();
    public static final int PREPECTFULPOLITEINCONVO = AttributesEnum.PRepectfulPoliteInConvo.index();
    public static final int PEASYTOWORK = AttributesEnum.PEasyToWork.index();
    public static final int PRESPONSIBLE = AttributesEnum.PResponsible.index();
    public static final int PCOOPERATES = AttributesEnum.PCooperates.index();
    public static final int PSHARESINFO = AttributesEnum.PSharesInfo.index();
    public static final int LINEMANAGERID = AttributesEnum.LineManagerId.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int PGENERALCOMMENTSPEERS = AttributesEnum.PGeneralCommentsPeers.index();
    public static final int HODREMARKS = AttributesEnum.HodRemarks.index();
    public static final int SUBMITIONDATE = AttributesEnum.SubmitionDate.index();
    public static final int POSTED_BOOLEAN = AttributesEnum.posted_boolean.index();
    public static final int VO_SEARCHEMPLOYEE1 = AttributesEnum.VO_SearchEmployee1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VO_XXSubOrdFormRowImpl() {
    }

    /**
     * Gets EO_XXSubOrdForm entity object.
     * @return the EO_XXSubOrdForm
     */
    public EO_XXSubOrdFormImpl getEO_XXSubOrdForm() {
        return (EO_XXSubOrdFormImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for FORM_ID using the alias name FormId.
     * @return the FORM_ID
     */
    public Number getFormId() {
        return (Number) getAttributeInternal(FORMID);
    }

    /**
     * Sets <code>value</code> as attribute value for FORM_ID using the alias name FormId.
     * @param value value to set the FORM_ID
     */
    public void setFormId(Number value) {
        setAttributeInternal(FORMID, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_DEPARTMENT using the alias name EmployeeDepartment.
     * @return the EMPLOYEE_DEPARTMENT
     */
    public String getEmployeeDepartment() {
        return (String) getAttributeInternal(EMPLOYEEDEPARTMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_DEPARTMENT using the alias name EmployeeDepartment.
     * @param value value to set the EMPLOYEE_DEPARTMENT
     */
    public void setEmployeeDepartment(String value) {
        setAttributeInternal(EMPLOYEEDEPARTMENT, value);
    }

    /**
     * Gets the attribute value for LINE_MANAGER_NAME using the alias name LineManagerName.
     * @return the LINE_MANAGER_NAME
     */
    public String getLineManagerName() {
        return (String) getAttributeInternal(LINEMANAGERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_MANAGER_NAME using the alias name LineManagerName.
     * @param value value to set the LINE_MANAGER_NAME
     */
    public void setLineManagerName(String value) {
        setAttributeInternal(LINEMANAGERNAME, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_NO using the alias name EmployeeNo.
     * @return the EMPLOYEE_NO
     */
    public String getEmployeeNo() {
        return (String) getAttributeInternal(EMPLOYEENO);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_NO using the alias name EmployeeNo.
     * @param value value to set the EMPLOYEE_NO
     */
    public void setEmployeeNo(String value) {
        setAttributeInternal(EMPLOYEENO, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_NAME using the alias name EmployeeName.
     * @return the EMPLOYEE_NAME
     */
    public String getEmployeeName() {
        return (String) getAttributeInternal(EMPLOYEENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_NAME using the alias name EmployeeName.
     * @param value value to set the EMPLOYEE_NAME
     */
    public void setEmployeeName(String value) {
        setAttributeInternal(EMPLOYEENAME, value);
    }

    /**
     * Gets the attribute value for EMP_QUALIFICATION using the alias name EmpQualification.
     * @return the EMP_QUALIFICATION
     */
    public String getEmpQualification() {
        return (String) getAttributeInternal(EMPQUALIFICATION);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_QUALIFICATION using the alias name EmpQualification.
     * @param value value to set the EMP_QUALIFICATION
     */
    public void setEmpQualification(String value) {
        setAttributeInternal(EMPQUALIFICATION, value);
    }

    /**
     * Gets the attribute value for EMP_DESIGNATION using the alias name EmpDesignation.
     * @return the EMP_DESIGNATION
     */
    public String getEmpDesignation() {
        return (String) getAttributeInternal(EMPDESIGNATION);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_DESIGNATION using the alias name EmpDesignation.
     * @param value value to set the EMP_DESIGNATION
     */
    public void setEmpDesignation(String value) {
        setAttributeInternal(EMPDESIGNATION, value);
    }

    /**
     * Gets the attribute value for EMP_DOJ using the alias name EmpDoj.
     * @return the EMP_DOJ
     */
    public Date getEmpDoj() {
        return (Date) getAttributeInternal(EMPDOJ);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_DOJ using the alias name EmpDoj.
     * @param value value to set the EMP_DOJ
     */
    public void setEmpDoj(Date value) {
        setAttributeInternal(EMPDOJ, value);
    }

    /**
     * Gets the attribute value for LAST_PROMOTION_DATE using the alias name LastPromotionDate.
     * @return the LAST_PROMOTION_DATE
     */
    public Date getLastPromotionDate() {
        return (Date) getAttributeInternal(LASTPROMOTIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_PROMOTION_DATE using the alias name LastPromotionDate.
     * @param value value to set the LAST_PROMOTION_DATE
     */
    public void setLastPromotionDate(Date value) {
        setAttributeInternal(LASTPROMOTIONDATE, value);
    }

    /**
     * Gets the attribute value for COMMERCIAL_JUDGMENT using the alias name CommercialJudgment.
     * @return the COMMERCIAL_JUDGMENT
     */
    public String getCommercialJudgment() {
        return (String) getAttributeInternal(COMMERCIALJUDGMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMERCIAL_JUDGMENT using the alias name CommercialJudgment.
     * @param value value to set the COMMERCIAL_JUDGMENT
     */
    public void setCommercialJudgment(String value) {
        setAttributeInternal(COMMERCIALJUDGMENT, value);
    }

    /**
     * Gets the attribute value for PRODUCT_TECHNICAL_KNOWLEDGE using the alias name ProductTechnicalKnowledge.
     * @return the PRODUCT_TECHNICAL_KNOWLEDGE
     */
    public String getProductTechnicalKnowledge() {
        return (String) getAttributeInternal(PRODUCTTECHNICALKNOWLEDGE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_TECHNICAL_KNOWLEDGE using the alias name ProductTechnicalKnowledge.
     * @param value value to set the PRODUCT_TECHNICAL_KNOWLEDGE
     */
    public void setProductTechnicalKnowledge(String value) {
        setAttributeInternal(PRODUCTTECHNICALKNOWLEDGE, value);
    }

    /**
     * Gets the attribute value for TIME_MANAGEMENT using the alias name TimeManagement.
     * @return the TIME_MANAGEMENT
     */
    public String getTimeManagement() {
        return (String) getAttributeInternal(TIMEMANAGEMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for TIME_MANAGEMENT using the alias name TimeManagement.
     * @param value value to set the TIME_MANAGEMENT
     */
    public void setTimeManagement(String value) {
        setAttributeInternal(TIMEMANAGEMENT, value);
    }

    /**
     * Gets the attribute value for COMMUNICATION_SKILLS using the alias name CommunicationSkills.
     * @return the COMMUNICATION_SKILLS
     */
    public String getCommunicationSkills() {
        return (String) getAttributeInternal(COMMUNICATIONSKILLS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMUNICATION_SKILLS using the alias name CommunicationSkills.
     * @param value value to set the COMMUNICATION_SKILLS
     */
    public void setCommunicationSkills(String value) {
        setAttributeInternal(COMMUNICATIONSKILLS, value);
    }

    /**
     * Gets the attribute value for DELEGATION_SKILLS using the alias name DelegationSkills.
     * @return the DELEGATION_SKILLS
     */
    public String getDelegationSkills() {
        return (String) getAttributeInternal(DELEGATIONSKILLS);
    }

    /**
     * Sets <code>value</code> as attribute value for DELEGATION_SKILLS using the alias name DelegationSkills.
     * @param value value to set the DELEGATION_SKILLS
     */
    public void setDelegationSkills(String value) {
        setAttributeInternal(DELEGATIONSKILLS, value);
    }

    /**
     * Gets the attribute value for MEETING_DEADLINES using the alias name MeetingDeadlines.
     * @return the MEETING_DEADLINES
     */
    public String getMeetingDeadlines() {
        return (String) getAttributeInternal(MEETINGDEADLINES);
    }

    /**
     * Sets <code>value</code> as attribute value for MEETING_DEADLINES using the alias name MeetingDeadlines.
     * @param value value to set the MEETING_DEADLINES
     */
    public void setMeetingDeadlines(String value) {
        setAttributeInternal(MEETINGDEADLINES, value);
    }

    /**
     * Gets the attribute value for COMMITMENT_TO_WORK using the alias name CommitmentToWork.
     * @return the COMMITMENT_TO_WORK
     */
    public String getCommitmentToWork() {
        return (String) getAttributeInternal(COMMITMENTTOWORK);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMITMENT_TO_WORK using the alias name CommitmentToWork.
     * @param value value to set the COMMITMENT_TO_WORK
     */
    public void setCommitmentToWork(String value) {
        setAttributeInternal(COMMITMENTTOWORK, value);
    }

    /**
     * Gets the attribute value for CREATIVITY using the alias name Creativity.
     * @return the CREATIVITY
     */
    public String getCreativity() {
        return (String) getAttributeInternal(CREATIVITY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATIVITY using the alias name Creativity.
     * @param value value to set the CREATIVITY
     */
    public void setCreativity(String value) {
        setAttributeInternal(CREATIVITY, value);
    }

    /**
     * Gets the attribute value for PROBLEM_SOLVING using the alias name ProblemSolving.
     * @return the PROBLEM_SOLVING
     */
    public String getProblemSolving() {
        return (String) getAttributeInternal(PROBLEMSOLVING);
    }

    /**
     * Sets <code>value</code> as attribute value for PROBLEM_SOLVING using the alias name ProblemSolving.
     * @param value value to set the PROBLEM_SOLVING
     */
    public void setProblemSolving(String value) {
        setAttributeInternal(PROBLEMSOLVING, value);
    }

    /**
     * Gets the attribute value for TAKING_INITIATIVE using the alias name TakingInitiative.
     * @return the TAKING_INITIATIVE
     */
    public String getTakingInitiative() {
        return (String) getAttributeInternal(TAKINGINITIATIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for TAKING_INITIATIVE using the alias name TakingInitiative.
     * @param value value to set the TAKING_INITIATIVE
     */
    public void setTakingInitiative(String value) {
        setAttributeInternal(TAKINGINITIATIVE, value);
    }

    /**
     * Gets the attribute value for DECISION_MAKING using the alias name DecisionMaking.
     * @return the DECISION_MAKING
     */
    public String getDecisionMaking() {
        return (String) getAttributeInternal(DECISIONMAKING);
    }

    /**
     * Sets <code>value</code> as attribute value for DECISION_MAKING using the alias name DecisionMaking.
     * @param value value to set the DECISION_MAKING
     */
    public void setDecisionMaking(String value) {
        setAttributeInternal(DECISIONMAKING, value);
    }

    /**
     * Gets the attribute value for TEAM_WORK using the alias name TeamWork.
     * @return the TEAM_WORK
     */
    public String getTeamWork() {
        return (String) getAttributeInternal(TEAMWORK);
    }

    /**
     * Sets <code>value</code> as attribute value for TEAM_WORK using the alias name TeamWork.
     * @param value value to set the TEAM_WORK
     */
    public void setTeamWork(String value) {
        setAttributeInternal(TEAMWORK, value);
    }

    /**
     * Gets the attribute value for DEVELOPING_OTHERS using the alias name DevelopingOthers.
     * @return the DEVELOPING_OTHERS
     */
    public String getDevelopingOthers() {
        return (String) getAttributeInternal(DEVELOPINGOTHERS);
    }

    /**
     * Sets <code>value</code> as attribute value for DEVELOPING_OTHERS using the alias name DevelopingOthers.
     * @param value value to set the DEVELOPING_OTHERS
     */
    public void setDevelopingOthers(String value) {
        setAttributeInternal(DEVELOPINGOTHERS, value);
    }

    /**
     * Gets the attribute value for LEADERSHIP using the alias name Leadership.
     * @return the LEADERSHIP
     */
    public String getLeadership() {
        return (String) getAttributeInternal(LEADERSHIP);
    }

    /**
     * Sets <code>value</code> as attribute value for LEADERSHIP using the alias name Leadership.
     * @param value value to set the LEADERSHIP
     */
    public void setLeadership(String value) {
        setAttributeInternal(LEADERSHIP, value);
    }

    /**
     * Gets the attribute value for INTEGRITY using the alias name Integrity.
     * @return the INTEGRITY
     */
    public String getIntegrity() {
        return (String) getAttributeInternal(INTEGRITY);
    }

    /**
     * Sets <code>value</code> as attribute value for INTEGRITY using the alias name Integrity.
     * @param value value to set the INTEGRITY
     */
    public void setIntegrity(String value) {
        setAttributeInternal(INTEGRITY, value);
    }

    /**
     * Gets the attribute value for STABILITY_UNDER_PRESSURE using the alias name StabilityUnderPressure.
     * @return the STABILITY_UNDER_PRESSURE
     */
    public String getStabilityUnderPressure() {
        return (String) getAttributeInternal(STABILITYUNDERPRESSURE);
    }

    /**
     * Sets <code>value</code> as attribute value for STABILITY_UNDER_PRESSURE using the alias name StabilityUnderPressure.
     * @param value value to set the STABILITY_UNDER_PRESSURE
     */
    public void setStabilityUnderPressure(String value) {
        setAttributeInternal(STABILITYUNDERPRESSURE, value);
    }

    /**
     * Gets the attribute value for ATTITUDE_TOWARDS_AUTHORITY using the alias name AttitudeTowardsAuthority.
     * @return the ATTITUDE_TOWARDS_AUTHORITY
     */
    public String getAttitudeTowardsAuthority() {
        return (String) getAttributeInternal(ATTITUDETOWARDSAUTHORITY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTITUDE_TOWARDS_AUTHORITY using the alias name AttitudeTowardsAuthority.
     * @param value value to set the ATTITUDE_TOWARDS_AUTHORITY
     */
    public void setAttitudeTowardsAuthority(String value) {
        setAttributeInternal(ATTITUDETOWARDSAUTHORITY, value);
    }

    /**
     * Gets the attribute value for LOYALTY using the alias name Loyalty.
     * @return the LOYALTY
     */
    public String getLoyalty() {
        return (String) getAttributeInternal(LOYALTY);
    }

    /**
     * Sets <code>value</code> as attribute value for LOYALTY using the alias name Loyalty.
     * @param value value to set the LOYALTY
     */
    public void setLoyalty(String value) {
        setAttributeInternal(LOYALTY, value);
    }

    /**
     * Gets the attribute value for ABILITY_TO_LEARN using the alias name AbilityToLearn.
     * @return the ABILITY_TO_LEARN
     */
    public String getAbilityToLearn() {
        return (String) getAttributeInternal(ABILITYTOLEARN);
    }

    /**
     * Sets <code>value</code> as attribute value for ABILITY_TO_LEARN using the alias name AbilityToLearn.
     * @param value value to set the ABILITY_TO_LEARN
     */
    public void setAbilityToLearn(String value) {
        setAttributeInternal(ABILITYTOLEARN, value);
    }

    /**
     * Gets the attribute value for ACCEPTING_CHANGE using the alias name AcceptingChange.
     * @return the ACCEPTING_CHANGE
     */
    public String getAcceptingChange() {
        return (String) getAttributeInternal(ACCEPTINGCHANGE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCEPTING_CHANGE using the alias name AcceptingChange.
     * @param value value to set the ACCEPTING_CHANGE
     */
    public void setAcceptingChange(String value) {
        setAttributeInternal(ACCEPTINGCHANGE, value);
    }

    /**
     * Gets the attribute value for P_REPECTFUL_POLITE_IN_CONVO using the alias name PRepectfulPoliteInConvo.
     * @return the P_REPECTFUL_POLITE_IN_CONVO
     */
    public String getPRepectfulPoliteInConvo() {
        return (String) getAttributeInternal(PREPECTFULPOLITEINCONVO);
    }

    /**
     * Sets <code>value</code> as attribute value for P_REPECTFUL_POLITE_IN_CONVO using the alias name PRepectfulPoliteInConvo.
     * @param value value to set the P_REPECTFUL_POLITE_IN_CONVO
     */
    public void setPRepectfulPoliteInConvo(String value) {
        setAttributeInternal(PREPECTFULPOLITEINCONVO, value);
    }

    /**
     * Gets the attribute value for P_EASY_TO_WORK using the alias name PEasyToWork.
     * @return the P_EASY_TO_WORK
     */
    public String getPEasyToWork() {
        return (String) getAttributeInternal(PEASYTOWORK);
    }

    /**
     * Sets <code>value</code> as attribute value for P_EASY_TO_WORK using the alias name PEasyToWork.
     * @param value value to set the P_EASY_TO_WORK
     */
    public void setPEasyToWork(String value) {
        setAttributeInternal(PEASYTOWORK, value);
    }

    /**
     * Gets the attribute value for P_RESPONSIBLE using the alias name PResponsible.
     * @return the P_RESPONSIBLE
     */
    public String getPResponsible() {
        return (String) getAttributeInternal(PRESPONSIBLE);
    }

    /**
     * Sets <code>value</code> as attribute value for P_RESPONSIBLE using the alias name PResponsible.
     * @param value value to set the P_RESPONSIBLE
     */
    public void setPResponsible(String value) {
        setAttributeInternal(PRESPONSIBLE, value);
    }

    /**
     * Gets the attribute value for P_COOPERATES using the alias name PCooperates.
     * @return the P_COOPERATES
     */
    public String getPCooperates() {
        return (String) getAttributeInternal(PCOOPERATES);
    }

    /**
     * Sets <code>value</code> as attribute value for P_COOPERATES using the alias name PCooperates.
     * @param value value to set the P_COOPERATES
     */
    public void setPCooperates(String value) {
        setAttributeInternal(PCOOPERATES, value);
    }

    /**
     * Gets the attribute value for P_SHARES_INFO using the alias name PSharesInfo.
     * @return the P_SHARES_INFO
     */
    public String getPSharesInfo() {
        return (String) getAttributeInternal(PSHARESINFO);
    }

    /**
     * Sets <code>value</code> as attribute value for P_SHARES_INFO using the alias name PSharesInfo.
     * @param value value to set the P_SHARES_INFO
     */
    public void setPSharesInfo(String value) {
        setAttributeInternal(PSHARESINFO, value);
    }

    /**
     * Gets the attribute value for P_GENERAL_COMMENTS_PEERS using the alias name PGeneralCommentsPeers.
     * @return the P_GENERAL_COMMENTS_PEERS
     */
    public String getPGeneralCommentsPeers() {
        return (String) getAttributeInternal(PGENERALCOMMENTSPEERS);
    }

    /**
     * Sets <code>value</code> as attribute value for P_GENERAL_COMMENTS_PEERS using the alias name PGeneralCommentsPeers.
     * @param value value to set the P_GENERAL_COMMENTS_PEERS
     */
    public void setPGeneralCommentsPeers(String value) {
        setAttributeInternal(PGENERALCOMMENTSPEERS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute HodRemarks.
     * @return the HodRemarks
     */
    public String getHodRemarks() {
        return (String) getAttributeInternal(HODREMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HodRemarks.
     * @param value value to set the  HodRemarks
     */
    public void setHodRemarks(String value) {
        setAttributeInternal(HODREMARKS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute posted_boolean.
     * @return the posted_boolean
     */
    public Boolean getposted_boolean() {
        boolean b = false;
        if (getPosted() == null) {
            b = false;
        }else if (getPosted().equals("YES")) {
            b = true;
        }
        return b;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute posted_boolean.
     * @param value value to set the  posted_boolean
     */
    public void setposted_boolean(Boolean value) {
        if(value) {
            setPosted("YES");
        }else{
            setPosted(null);
        }
    }


    /**
     * Gets the attribute value for SUBMITION_DATE using the alias name SubmitionDate.
     * @return the SUBMITION_DATE
     */
    public Date getSubmitionDate() {
        return (Date) getAttributeInternal(SUBMITIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMITION_DATE using the alias name SubmitionDate.
     * @param value value to set the SUBMITION_DATE
     */
    public void setSubmitionDate(Date value) {
        setAttributeInternal(SUBMITIONDATE, value);
    }

    /**
     * Gets the attribute value for POSTED using the alias name Posted.
     * @return the POSTED
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTED using the alias name Posted.
     * @param value value to set the POSTED
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for LINE_MANAGER_ID using the alias name LineManagerId.
     * @return the LINE_MANAGER_ID
     */
    public String getLineManagerId() {
        return (String) getAttributeInternal(LINEMANAGERID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_MANAGER_ID using the alias name LineManagerId.
     * @param value value to set the LINE_MANAGER_ID
     */
    public void setLineManagerId(String value) {
        setAttributeInternal(LINEMANAGERID, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_SearchEmployee1.
     */
    public RowSet getVO_SearchEmployee1() {
        return (RowSet)getAttributeInternal(VO_SEARCHEMPLOYEE1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
